<?php

namespace AppBundle\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20171008015301 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE access_token (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, account_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_B6A2DD685F37A13B (token), INDEX IDX_B6A2DD6819EB6921 (client_id), INDEX IDX_B6A2DD689B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gender (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE billing_categories (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, default_value VARCHAR(255) NOT NULL, report_name VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_upd VARCHAR(255) NOT NULL, updated_by_id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transport_orders (id INT AUTO_INCREMENT NOT NULL, vendor_id INT NOT NULL, customer_id INT NOT NULL, party_id INT NOT NULL, vehicle_capacity VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, class VARCHAR(255) NOT NULL, vehicle_numbers VARCHAR(255) NOT NULL, id_address VARCHAR(255) NOT NULL, vehicle_id INT NOT NULL, id_currency VARCHAR(255) NOT NULL, reference VARCHAR(255) NOT NULL, current_state VARCHAR(255) NOT NULL, conversion_rate VARCHAR(255) NOT NULL, recyclable VARCHAR(255) NOT NULL, gift VARCHAR(255) NOT NULL, gift_notes VARCHAR(255) NOT NULL, notes VARCHAR(255) NOT NULL, tracking_number VARCHAR(255) NOT NULL, total_discounts VARCHAR(255) NOT NULL, total_discounts_tax_incl VARCHAR(255) NOT NULL, total_discounts_tax_excl VARCHAR(255) NOT NULL, total_paid VARCHAR(255) NOT NULL, total_paid_tax_incl VARCHAR(255) NOT NULL, total_paid_tax_excl VARCHAR(255) NOT NULL, total_paid_real VARCHAR(255) NOT NULL, total_tran_cost VARCHAR(255) NOT NULL, valid VARCHAR(255) NOT NULL, date_add VARCHAR(255) NOT NULL, date_upd VARCHAR(255) NOT NULL, deleted VARCHAR(255) NOT NULL, reservation_date DATETIME NOT NULL, reservation_no VARCHAR(255) NOT NULL, reservation_status VARCHAR(255) NOT NULL, deployment_date VARCHAR(255) NOT NULL, deployment_status VARCHAR(255) NOT NULL, payment VARCHAR(255) NOT NULL, modules VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_descriptions (id INT AUTO_INCREMENT NOT NULL, lang_id INT NOT NULL, name VARCHAR(255) NOT NULL, meta_keywords VARCHAR(255) NOT NULL, meta_description VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, blurb VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_invitations (id INT AUTO_INCREMENT NOT NULL, event_id INT NOT NULL, contact_id INT NOT NULL, synced TINYINT(1) NOT NULL, special_id INT NOT NULL, is_enabled TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, is_suspended TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vendor (id INT AUTO_INCREMENT NOT NULL, account_id INT NOT NULL, id_state VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, address1 VARCHAR(255) NOT NULL, address2 VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, postcode VARCHAR(255) NOT NULL, latitude VARCHAR(255) NOT NULL, longitude VARCHAR(255) NOT NULL, hours VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, fax VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, note VARCHAR(255) NOT NULL, active VARCHAR(255) NOT NULL, date_add VARCHAR(255) NOT NULL, date_upd VARCHAR(255) NOT NULL, suspended VARCHAR(255) NOT NULL, deleted VARCHAR(255) NOT NULL, vendorDescriptions INT DEFAULT NULL, UNIQUE INDEX UNIQ_F52233F65CAE469F (vendorDescriptions), UNIQUE INDEX UNIQ_F52233F69B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE carrier (id INT AUTO_INCREMENT NOT NULL, id_reference VARCHAR(255) NOT NULL, id_tax_rules_group VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, active VARCHAR(255) NOT NULL, deleted VARCHAR(255) NOT NULL, suspended VARCHAR(255) NOT NULL, shipping_handling VARCHAR(255) NOT NULL, range_behavior VARCHAR(255) NOT NULL, is_module TINYINT(1) NOT NULL, is_free TINYINT(1) NOT NULL, shipping_external VARCHAR(255) NOT NULL, need_range VARCHAR(255) NOT NULL, external_module_name VARCHAR(255) NOT NULL, shipping_method VARCHAR(255) NOT NULL, position VARCHAR(255) NOT NULL, max_width VARCHAR(255) NOT NULL, max_height VARCHAR(255) NOT NULL, max_depth VARCHAR(255) NOT NULL, max_weight VARCHAR(255) NOT NULL, grade VARCHAR(255) NOT NULL, _group VARCHAR(255) NOT NULL, language VARCHAR(255) NOT NULL, vendor VARCHAR(255) NOT NULL, tax_rules_group_vendor VARCHAR(255) NOT NULL, zone VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service (id INT AUTO_INCREMENT NOT NULL, vendor_id INT NOT NULL, manufacturer_id INT NOT NULL, category_default_id INT NOT NULL, vendor_default_id INT NOT NULL, tax_rules_id INT NOT NULL, on_sale VARCHAR(255) NOT NULL, approved VARCHAR(255) NOT NULL, deleted VARCHAR(255) NOT NULL, suspended VARCHAR(255) NOT NULL, quantity VARCHAR(255) NOT NULL, minimal_quantiy VARCHAR(255) NOT NULL, price VARCHAR(255) NOT NULL, wholesale_price VARCHAR(255) NOT NULL, wholesale_threshold VARCHAR(255) NOT NULL, unit_price_ratio NUMERIC(10, 0) NOT NULL, additional_shipping_cost VARCHAR(255) NOT NULL, reference VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, loc_coordinates VARCHAR(255) NOT NULL, width VARCHAR(255) NOT NULL, height VARCHAR(255) NOT NULL, weight VARCHAR(255) NOT NULL, lenght VARCHAR(255) NOT NULL, out_of_stock NUMERIC(10, 0) NOT NULL, quantity_discount VARCHAR(255) NOT NULL, customizable VARCHAR(255) NOT NULL, uploaded_files VARCHAR(255) NOT NULL, text_fields VARCHAR(255) NOT NULL, active VARCHAR(255) NOT NULL, redirect_type VARCHAR(255) NOT NULL, id_product_redirected VARCHAR(255) NOT NULL, available_for_order VARCHAR(255) NOT NULL, available_date VARCHAR(255) NOT NULL, service_condition VARCHAR(255) NOT NULL, show_price VARCHAR(255) NOT NULL, indexed VARCHAR(255) NOT NULL, visibility VARCHAR(255) NOT NULL, date_add VARCHAR(255) NOT NULL, date_upd VARCHAR(255) NOT NULL, advanced_stock_managementt VARCHAR(255) NOT NULL, pack_stock_type VARCHAR(255) NOT NULL, attachments VARCHAR(255) NOT NULL, attribute VARCHAR(255) NOT NULL, attribute_combination VARCHAR(255) NOT NULL, attribute_image VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, class VARCHAR(255) NOT NULL, attribute_vendor VARCHAR(255) NOT NULL, carrier VARCHAR(255) NOT NULL, country_tax VARCHAR(255) NOT NULL, download VARCHAR(255) NOT NULL, vendor_reduction_cache VARCHAR(255) NOT NULL, language VARCHAR(255) NOT NULL, sale VARCHAR(255) NOT NULL, vendor VARCHAR(255) NOT NULL, supplier VARCHAR(255) NOT NULL, tag VARCHAR(255) NOT NULL, products VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_campaigns (service_id INT NOT NULL, campaigns_id INT NOT NULL, INDEX IDX_BBE24E3AED5CA9E6 (service_id), INDEX IDX_BBE24E3AB0EF31F7 (campaigns_id), PRIMARY KEY(service_id, campaigns_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE zone_descriptions (id INT AUTO_INCREMENT NOT NULL, lang_id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stock (id INT AUTO_INCREMENT NOT NULL, id_warehouse VARCHAR(255) NOT NULL, id_product VARCHAR(255) NOT NULL, id_product_attribute VARCHAR(255) NOT NULL, reference VARCHAR(255) NOT NULL, physical_quantity VARCHAR(255) NOT NULL, usable_quantity VARCHAR(255) NOT NULL, price VARCHAR(255) NOT NULL, available VARCHAR(255) NOT NULL, mvt VARCHAR(255) NOT NULL, mvt_reason VARCHAR(255) NOT NULL, mvt_reason_lang VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tax_rates (id INT AUTO_INCREMENT NOT NULL, location_id INT NOT NULL, zone_id INT NOT NULL, tax_class_id INT NOT NULL, priority INT NOT NULL, rate NUMERIC(10, 0) NOT NULL, rate_prefix VARCHAR(255) NOT NULL, threshold_condition VARCHAR(255) NOT NULL, theshold NUMERIC(10, 0) NOT NULL, tax_exempt_groups VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, taxRateDescriptions INT DEFAULT NULL, UNIQUE INDEX UNIQ_F7AE5E1D3F3A0FD9 (taxRateDescriptions), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_discounts (id INT AUTO_INCREMENT NOT NULL, service_discount_id INT NOT NULL, service_id INT NOT NULL, customer_group_id INT NOT NULL, quantity INT NOT NULL, priority INT NOT NULL, price NUMERIC(10, 0) NOT NULL, date_start DATETIME NOT NULL, date_end DATETIME NOT NULL, date_added DATETIME NOT NULL, date_modified DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tax_classes (id INT AUTO_INCREMENT NOT NULL, date_add VARCHAR(255) NOT NULL, date_upd VARCHAR(255) NOT NULL, taxClassDescriptions INT DEFAULT NULL, UNIQUE INDEX UNIQ_43A5DECFBC6DC00D (taxClassDescriptions), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE party_editor (id INT AUTO_INCREMENT NOT NULL, vendor_group VARCHAR(255) NOT NULL, vendor VARCHAR(255) NOT NULL, id_carrier VARCHAR(255) NOT NULL, delivery_option VARCHAR(255) NOT NULL, id_lang VARCHAR(255) NOT NULL, id_address_delivery VARCHAR(255) NOT NULL, id_address_invoice VARCHAR(255) NOT NULL, id_currency VARCHAR(255) NOT NULL, id_customer VARCHAR(255) NOT NULL, id_guest VARCHAR(255) NOT NULL, recyclable VARCHAR(255) NOT NULL, gift VARCHAR(255) NOT NULL, gift_notes VARCHAR(255) NOT NULL, allow_seperated_package VARCHAR(255) NOT NULL, date_add VARCHAR(255) NOT NULL, date_upd VARCHAR(255) NOT NULL, deleted VARCHAR(255) NOT NULL, cart_rule VARCHAR(255) NOT NULL, service VARCHAR(255) NOT NULL, rule VARCHAR(255) NOT NULL, rule_carrier VARCHAR(255) NOT NULL, rule_combination VARCHAR(255) NOT NULL, rule_country VARCHAR(255) NOT NULL, rule_group VARCHAR(255) NOT NULL, rule_language VARCHAR(255) NOT NULL, rule_product_rule VARCHAR(255) NOT NULL, rule_service_rule_group VARCHAR(255) NOT NULL, rule_service_rule_value VARCHAR(255) NOT NULL, rule_vendor VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE specific_price (id INT AUTO_INCREMENT NOT NULL, id_specific_price_rule VARCHAR(255) NOT NULL, id_cart VARCHAR(255) NOT NULL, id_product VARCHAR(255) NOT NULL, id_vendor VARCHAR(255) NOT NULL, id_vendor_group VARCHAR(255) NOT NULL, id_currency VARCHAR(255) NOT NULL, id_country VARCHAR(255) NOT NULL, id_group VARCHAR(255) NOT NULL, id_customer VARCHAR(255) NOT NULL, id_product_attribute VARCHAR(255) NOT NULL, price VARCHAR(255) NOT NULL, from_quantity VARCHAR(255) NOT NULL, reduction VARCHAR(255) NOT NULL, reduction_tax VARCHAR(255) NOT NULL, reduction_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE auth_code (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, redirect_uri LONGTEXT NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_5933D02C5F37A13B (token), INDEX IDX_5933D02C19EB6921 (client_id), INDEX IDX_5933D02CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE food_orders (id INT AUTO_INCREMENT NOT NULL, party_id INT NOT NULL, vendor_id INT NOT NULL, quantity VARCHAR(255) NOT NULL, food_id INT NOT NULL, class VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, size VARCHAR(255) NOT NULL, id_lang VARCHAR(255) NOT NULL, id_customer VARCHAR(255) NOT NULL, id_currency VARCHAR(255) NOT NULL, reference VARCHAR(255) NOT NULL, id_warehouse VARCHAR(255) NOT NULL, current_state VARCHAR(255) NOT NULL, notes VARCHAR(255) NOT NULL, conversion_rate VARCHAR(255) NOT NULL, recyclable INT NOT NULL, gift VARCHAR(255) NOT NULL, gift_note VARCHAR(255) NOT NULL, tracking_number VARCHAR(255) NOT NULL, total_discounts VARCHAR(255) NOT NULL, total_discount_tax_incl VARCHAR(255) NOT NULL, total_discount_tax_excl VARCHAR(255) NOT NULL, total_paid VARCHAR(255) NOT NULL, total_paid_real VARCHAR(255) NOT NULL, total_food_cost VARCHAR(255) NOT NULL, valid VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_upd VARCHAR(255) NOT NULL, deleted VARCHAR(255) NOT NULL, reservation_date VARCHAR(255) NOT NULL, reservation_no VARCHAR(255) NOT NULL, reservation_approved VARCHAR(255) NOT NULL, deployment_date DATETIME NOT NULL, deployment_status DATETIME NOT NULL, payment VARCHAR(255) NOT NULL, module VARCHAR(255) NOT NULL, note VARCHAR(255) NOT NULL, food_paid VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE campaign_attachments (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, campaign VARCHAR(255) NOT NULL, media VARCHAR(255) NOT NULL, is_audio TINYINT(1) NOT NULL, is_image TINYINT(1) NOT NULL, is_video TINYINT(1) NOT NULL, is_enabled TINYINT(1) NOT NULL, is_suspended TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_9F0EC62CF639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pre_registration (id INT AUTO_INCREMENT NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, phone_number INT NOT NULL, email VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, gender VARCHAR(255) NOT NULL, age_range_id INT NOT NULL, age INT NOT NULL, service_category_id_is_interested VARCHAR(255) NOT NULL, guest_id INT NOT NULL, customer_id INT NOT NULL, meta_title VARCHAR(255) NOT NULL, is_enabled TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, meta_description VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE live_parties (id INT AUTO_INCREMENT NOT NULL, account_id INT DEFAULT NULL, vendor_id INT DEFAULT NULL, party_id INT NOT NULL, live_url VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, is_live TINYINT(1) NOT NULL, deleted VARCHAR(255) NOT NULL, is_promoted TINYINT(1) NOT NULL, promotion_id INT NOT NULL, viewing_currently INT NOT NULL, viewers_ipadd VARCHAR(255) NOT NULL, comments VARCHAR(255) NOT NULL, rating INT NOT NULL, stars VARCHAR(255) NOT NULL, stars_actual VARCHAR(255) NOT NULL, featured_img VARCHAR(255) NOT NULL, vendorGroup_id INT DEFAULT NULL, INDEX IDX_C2BE587E9B6B5FBA (account_id), INDEX IDX_C2BE587EF603EE73 (vendor_id), INDEX IDX_C2BE587E6D1D6203 (vendorGroup_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_services (id INT AUTO_INCREMENT NOT NULL, order_id INT NOT NULL, service_id INT NOT NULL, name VARCHAR(255) NOT NULL, model VARCHAR(255) NOT NULL, sku VARCHAR(255) NOT NULL, price NUMERIC(10, 0) NOT NULL, total NUMERIC(10, 0) NOT NULL, tax NUMERIC(10, 0) NOT NULL, quantity INT NOT NULL, subtract INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE party (id INT AUTO_INCREMENT NOT NULL, zone_id_id INT DEFAULT NULL, partyeditor_id INT NOT NULL, link VARCHAR(255) NOT NULL, is_preregistered TINYINT(1) NOT NULL, vendor_id INT NOT NULL, vendors_groups_id INT NOT NULL, customer_id INT NOT NULL, is_secured TINYINT(1) NOT NULL, security_reg_id INT NOT NULL, coordinates_lat NUMERIC(10, 0) NOT NULL, coordinates_long NUMERIC(10, 0) NOT NULL, rating INT NOT NULL, party_rating INT NOT NULL, class VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, preregistration_number INT NOT NULL, meta_title VARCHAR(255) NOT NULL, meta_description VARCHAR(255) NOT NULL, rsvp VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, deleted TINYINT(1) NOT NULL, suspended TINYINT(1) NOT NULL, enabled TINYINT(1) NOT NULL, total_guest INT NOT NULL, total_cost NUMERIC(10, 0) NOT NULL, INDEX IDX_89954EE0D96A31F1 (zone_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orders (id INT AUTO_INCREMENT NOT NULL, invoice_id INT NOT NULL, invoice_prefix VARCHAR(255) NOT NULL, store_id INT NOT NULL, store_name VARCHAR(255) NOT NULL, store_url VARCHAR(255) NOT NULL, customer_id INT NOT NULL, customer_group_id INT NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, phone_number INT NOT NULL, email VARCHAR(255) NOT NULL, shipping_firstname VARCHAR(255) NOT NULL, shipping_lastname VARCHAR(255) NOT NULL, shipping_company VARCHAR(255) NOT NULL, shipping_address_1 VARCHAR(255) NOT NULL, shipping_address_2 VARCHAR(255) NOT NULL, shipping_city VARCHAR(255) NOT NULL, shipping_postcode VARCHAR(255) NOT NULL, shipping_zone VARCHAR(255) NOT NULL, shipping_zone_id INT NOT NULL, shipping_country VARCHAR(255) NOT NULL, shipping_country_id INT NOT NULL, shipping_address_format VARCHAR(255) NOT NULL, shipping_method VARCHAR(255) NOT NULL, shipping_method_key VARCHAR(255) NOT NULL, payment_firstname VARCHAR(255) NOT NULL, payment_lastname VARCHAR(255) NOT NULL, payment_company VARCHAR(255) NOT NULL, payment_address_1 VARCHAR(255) NOT NULL, payment_address_2 VARCHAR(255) NOT NULL, payment_city VARCHAR(255) NOT NULL, payment_postcode VARCHAR(255) NOT NULL, payment_zone VARCHAR(255) NOT NULL, payment_zone_id INT NOT NULL, payment_country VARCHAR(255) NOT NULL, payment_country_id INT NOT NULL, payment_address_format VARCHAR(255) NOT NULL, payment_method VARCHAR(255) NOT NULL, payment_method_key VARCHAR(255) NOT NULL, comment VARCHAR(255) NOT NULL, total NUMERIC(10, 0) NOT NULL, order_status_id INT NOT NULL, lang_id INT NOT NULL, currency_id INT NOT NULL, currency VARCHAR(255) NOT NULL, value NUMERIC(10, 0) NOT NULL, coupon_id INT NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, ip VARCHAR(255) NOT NULL, payment_method_data VARCHAR(255) NOT NULL, is_enabled TINYINT(1) NOT NULL, is_suspended TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_data (id INT AUTO_INCREMENT NOT NULL, order_id INT NOT NULL, data VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, orderDataTypes INT DEFAULT NULL, INDEX IDX_E002C974335238BF (orderDataTypes), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_history (id INT AUTO_INCREMENT NOT NULL, order_history_id INT NOT NULL, order_id INT NOT NULL, order_status_id INT NOT NULL, notify INT NOT NULL, comment VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customization (id INT AUTO_INCREMENT NOT NULL, id_product_attribute VARCHAR(255) NOT NULL, id_address_delivery VARCHAR(255) NOT NULL, id_cart VARCHAR(255) NOT NULL, id_product VARCHAR(255) NOT NULL, quantity VARCHAR(255) NOT NULL, quantity_refunded VARCHAR(255) NOT NULL, quantity_returned VARCHAR(255) NOT NULL, in_party_editor VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_option_value_descriptions (id INT AUTO_INCREMENT NOT NULL, lang_id INT NOT NULL, service_id INT NOT NULL, name VARCHAR(255) NOT NULL, grouped_attribute_names VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE services_filters (id INT AUTO_INCREMENT NOT NULL, filter_id INT NOT NULL, filter_type VARCHAR(255) NOT NULL, categories_hash VARCHAR(255) NOT NULL, feature_id INT NOT NULL, sort_order INT NOT NULL, status TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vendor_groups (id INT AUTO_INCREMENT NOT NULL, vendor_id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, priviledge VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, association_type VARCHAR(255) NOT NULL, association_id INT NOT NULL, uploaded_by VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, name_id INT NOT NULL, date_add VARCHAR(255) NOT NULL, date_upd DATETIME NOT NULL, private TINYINT(1) NOT NULL, description VARCHAR(255) NOT NULL, mimetype VARCHAR(255) NOT NULL, filesize VARCHAR(255) NOT NULL, drive TINYINT(1) NOT NULL, access_key VARCHAR(255) NOT NULL, image TINYINT(1) NOT NULL, audio TINYINT(1) NOT NULL, video TINYINT(1) NOT NULL, is_enabled TINYINT(1) NOT NULL, is_suspended TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_6A2CA10CF639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manufacturers (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, coordinate_lat NUMERIC(10, 0) NOT NULL, coordinate_long NUMERIC(10, 0) NOT NULL, is_enabled TINYINT(1) NOT NULL, is_suspended TINYINT(1) NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, promotion_id INT NOT NULL, rating INT NOT NULL, cred_rating INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tags (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE janitorial_services_orders (id INT AUTO_INCREMENT NOT NULL, vendor_id INT NOT NULL, party_id INT NOT NULL, customer_id INT NOT NULL, janitor_numbers VARCHAR(255) NOT NULL, notes VARCHAR(255) NOT NULL, janitor_notes VARCHAR(255) NOT NULL, id_currency VARCHAR(255) NOT NULL, reference VARCHAR(255) NOT NULL, current_state VARCHAR(255) NOT NULL, conversion_rate VARCHAR(255) NOT NULL, recyclable VARCHAR(255) NOT NULL, gift VARCHAR(255) NOT NULL, gift_notes VARCHAR(255) NOT NULL, tracking_number VARCHAR(255) NOT NULL, total_discounts VARCHAR(255) NOT NULL, total_discounts_tax_excl VARCHAR(255) NOT NULL, total_discounts_tax_incl VARCHAR(255) NOT NULL, total_paid VARCHAR(255) NOT NULL, total_paid_tax_excl VARCHAR(255) NOT NULL, total_paid_tax_incl VARCHAR(255) NOT NULL, total_paid_real VARCHAR(255) NOT NULL, total_janitor_cost VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, valid INT NOT NULL, deleted INT NOT NULL, reservation_date DATETIME NOT NULL, reservation_no VARCHAR(255) NOT NULL, reservation_approved VARCHAR(255) NOT NULL, deployment_date DATE NOT NULL, deployment_status INT NOT NULL, payment VARCHAR(255) NOT NULL, module VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE imports (id INT AUTO_INCREMENT NOT NULL, import_id INT NOT NULL, model_id INT NOT NULL, model_type VARCHAR(255) NOT NULL, timestamp DATETIME NOT NULL, is_enabled TINYINT(1) NOT NULL, is_suspended TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mc_orders (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, rating VARCHAR(255) NOT NULL, class VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, pricing VARCHAR(255) NOT NULL, currency VARCHAR(255) NOT NULL, language VARCHAR(255) NOT NULL, activated VARCHAR(255) NOT NULL, deleted VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE links (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, target VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, visible TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_filter_discriptions (id INT AUTO_INCREMENT NOT NULL, filter_id INT NOT NULL, value VARCHAR(255) NOT NULL, lang_id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operating_system (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_specials (id INT AUTO_INCREMENT NOT NULL, service_special_id INT NOT NULL, service_id INT NOT NULL, customer_group_id INT NOT NULL, priority INT NOT NULL, price NUMERIC(10, 0) NOT NULL, date_start DATETIME NOT NULL, date_end DATETIME NOT NULL, date_added DATETIME NOT NULL, date_modified DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mixologist_orders (id INT AUTO_INCREMENT NOT NULL, vendor_id INT NOT NULL, drinks_id INT NOT NULL, drinks_to_mix INT NOT NULL, party_id INT NOT NULL, id_currency INT NOT NULL, reference VARCHAR(255) NOT NULL, gift VARCHAR(255) NOT NULL, gift_note VARCHAR(255) NOT NULL, recyclable VARCHAR(255) NOT NULL, total_discounts VARCHAR(255) NOT NULL, total_discounts_tax_excl VARCHAR(255) NOT NULL, total_discounts_tax_incl VARCHAR(255) NOT NULL, total_paid VARCHAR(255) NOT NULL, total_paid_tax_incl VARCHAR(255) NOT NULL, total_paid_tax_excl VARCHAR(255) NOT NULL, total_paid_real VARCHAR(255) NOT NULL, total_mix_cost VARCHAR(255) NOT NULL, date_add VARCHAR(255) NOT NULL, date_upd VARCHAR(255) NOT NULL, valid INT NOT NULL, deleted INT NOT NULL, reservation_date DATE NOT NULL, reservation_no INT NOT NULL, reservation_approved VARCHAR(255) NOT NULL, deployment_date VARCHAR(255) NOT NULL, deployment_status VARCHAR(255) NOT NULL, mixologist_note VARCHAR(255) NOT NULL, order_note VARCHAR(255) NOT NULL, payment VARCHAR(255) NOT NULL, module VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE agency (id INT AUTO_INCREMENT NOT NULL, account_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, contact VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, logout_url VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, updated DATETIME NOT NULL, INDEX IDX_70C0C6E69B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_option_values (id INT AUTO_INCREMENT NOT NULL, service_option_id INT NOT NULL, service_id INT NOT NULL, group_id INT NOT NULL, sku VARCHAR(255) NOT NULL, quantity INT NOT NULL, subtarct TINYINT(1) NOT NULL, price NUMERIC(10, 0) NOT NULL, prefix VARCHAR(255) NOT NULL, weight NUMERIC(10, 0) NOT NULL, weight_type VARCHAR(255) NOT NULL, attribute_value_id INT NOT NULL, grouped_attribute_data VARCHAR(255) NOT NULL, sort_order INT NOT NULL, b VARCHAR(255) NOT NULL, serviceOptionValueDescriptions INT DEFAULT NULL, UNIQUE INDEX UNIQ_A948F4B318C90441 (serviceOptionValueDescriptions), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reviews (id INT AUTO_INCREMENT NOT NULL, review_id INT NOT NULL, service_id INT NOT NULL, customer_id INT NOT NULL, author VARCHAR(255) NOT NULL, text VARCHAR(255) NOT NULL, rating INT NOT NULL, status TINYINT(1) NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE drink_order (id INT AUTO_INCREMENT NOT NULL, drink_id INT NOT NULL, vendor_id INT NOT NULL, quantity VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, class VARCHAR(255) NOT NULL, drink_langg VARCHAR(255) NOT NULL, drink_currency VARCHAR(255) NOT NULL, id_warehouse VARCHAR(255) NOT NULL, id_warehouse_invoice VARCHAR(255) NOT NULL, payment VARCHAR(255) NOT NULL, module VARCHAR(255) NOT NULL, gift VARCHAR(255) NOT NULL, gift_message VARCHAR(255) NOT NULL, drink_size VARCHAR(255) NOT NULL, tracking_no VARCHAR(255) NOT NULL, total_discounts VARCHAR(255) NOT NULL, total_discounts_tax_incl VARCHAR(255) NOT NULL, total_discounts_tax_excl VARCHAR(255) NOT NULL, total_paid VARCHAR(255) NOT NULL, total_paid_tax_incl VARCHAR(255) NOT NULL, total_paid_tax_excl VARCHAR(255) NOT NULL, total_paid_real VARCHAR(255) NOT NULL, total_drinks_cost VARCHAR(255) NOT NULL, delivery_status VARCHAR(255) NOT NULL, party_id INT NOT NULL, customer_id INT NOT NULL, reference VARCHAR(255) NOT NULL, recyclable VARCHAR(255) NOT NULL, conversion_rate VARCHAR(255) NOT NULL, current_state VARCHAR(255) NOT NULL, valid VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_center (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, class VARCHAR(255) NOT NULL, pricing VARCHAR(255) NOT NULL, characteristics VARCHAR(255) NOT NULL, coordinates VARCHAR(255) NOT NULL, featured_images VARCHAR(255) NOT NULL, featured_videos VARCHAR(255) NOT NULL, documentaries VARCHAR(255) NOT NULL, language VARCHAR(255) NOT NULL, currency VARCHAR(255) NOT NULL, additional_services VARCHAR(255) NOT NULL, center_group VARCHAR(255) NOT NULL, vendor VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, notes VARCHAR(255) NOT NULL, carriers VARCHAR(255) DEFAULT NULL, customization VARCHAR(255) NOT NULL, badge VARCHAR(255) NOT NULL, accessory VARCHAR(255) NOT NULL, access VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE supply_order (id INT AUTO_INCREMENT NOT NULL, id_supplier VARCHAR(255) NOT NULL, supplier_name VARCHAR(255) NOT NULL, id_lang VARCHAR(255) NOT NULL, id_warehouse VARCHAR(255) NOT NULL, id_supply_order_state VARCHAR(255) NOT NULL, id_currency VARCHAR(255) NOT NULL, id_ref_currency VARCHAR(255) NOT NULL, reference VARCHAR(255) NOT NULL, date_add VARCHAR(255) NOT NULL, date_upd VARCHAR(255) NOT NULL, date_delivery_expected VARCHAR(255) NOT NULL, total_te VARCHAR(255) NOT NULL, total_with_discount_te VARCHAR(255) NOT NULL, total_tax VARCHAR(255) NOT NULL, total_ti VARCHAR(255) NOT NULL, discount_rate VARCHAR(255) NOT NULL, discount_value_te VARCHAR(255) NOT NULL, detail VARCHAR(255) NOT NULL, history VARCHAR(255) NOT NULL, receipt_history VARCHAR(255) NOT NULL, state VARCHAR(255) NOT NULL, state_lang VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE posts (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, content VARCHAR(1000) NOT NULL, publishedAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_approved TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bug_reports (id INT AUTO_INCREMENT NOT NULL, error_code VARCHAR(255) NOT NULL, visibility VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, severity INT NOT NULL, php_version VARCHAR(255) NOT NULL, line VARCHAR(255) NOT NULL, file VARCHAR(255) NOT NULL, dupliacte TINYINT(1) NOT NULL, blocks VARCHAR(255) NOT NULL, updated_by VARCHAR(255) NOT NULL, date_upd DATETIME NOT NULL, last_activity DATETIME NOT NULL, date_add DATETIME NOT NULL, description VARCHAR(255) NOT NULL, name_id INT NOT NULL, name VARCHAR(255) NOT NULL, assigned_to VARCHAR(255) NOT NULL, bug_report_id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE aso_ebi (id INT AUTO_INCREMENT NOT NULL, manufacturer_id INT DEFAULT NULL, vendor_id INT DEFAULT NULL, zone_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, deleted TINYINT(1) NOT NULL, price NUMERIC(6, 0) NOT NULL, price_discount_excl_tax NUMERIC(6, 0) NOT NULL, price_discount_incl_tax NUMERIC(6, 0) NOT NULL, taxable TINYINT(1) NOT NULL, featured_image TINYINT(1) NOT NULL, featured_video VARCHAR(255) NOT NULL, documentaries VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_edited DATETIME NOT NULL, is_promoted TINYINT(1) NOT NULL, promotion_id INT NOT NULL, coordinates_lat NUMERIC(10, 0) NOT NULL, coordinates_long NUMERIC(10, 0) NOT NULL, cred_rating INT NOT NULL, is_suspended TINYINT(1) NOT NULL, views_counts INT NOT NULL, warehouse_id INT NOT NULL, warehouse_mode_id INT NOT NULL, quantity INT NOT NULL, allow_oversell_percentage INT NOT NULL, tags VARCHAR(255) NOT NULL, meta_title VARCHAR(255) NOT NULL, meta_description VARCHAR(255) NOT NULL, INDEX IDX_98AEC13AA23B42D (manufacturer_id), INDEX IDX_98AEC13AF603EE73 (vendor_id), INDEX IDX_98AEC13A9F2C3FAB (zone_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_data (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL, count INT NOT NULL, user VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE account_details (id INT AUTO_INCREMENT NOT NULL, birthday DATETIME DEFAULT NULL, account_group_id INT NOT NULL, country_id INT NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, financial_id INT NOT NULL, newsletter_id INT NOT NULL, wishlist_id INT NOT NULL, created_from_ip VARCHAR(45) DEFAULT NULL, updated_from_ip VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notifications (id INT AUTO_INCREMENT NOT NULL, notification_id INT NOT NULL, app VARCHAR(255) NOT NULL, user VARCHAR(255) NOT NULL, timestamp DATETIME NOT NULL, object_type VARCHAR(255) NOT NULL, object_id INT NOT NULL, subject VARCHAR(255) NOT NULL, subject_parameters VARCHAR(255) NOT NULL, message VARCHAR(255) NOT NULL, message_parameters VARCHAR(255) NOT NULL, link VARCHAR(255) NOT NULL, icon VARCHAR(255) NOT NULL, actions VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE beauty_and_makeup_orders (id INT AUTO_INCREMENT NOT NULL, vendor_id INT NOT NULL, party_id INT NOT NULL, customer_id INT NOT NULL, clients_number VARCHAR(255) NOT NULL, sex VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, class VARCHAR(255) NOT NULL, beauty_notes VARCHAR(255) NOT NULL, reservation_date VARCHAR(255) NOT NULL, special_requirements VARCHAR(255) NOT NULL, reference VARCHAR(255) NOT NULL, id_currency VARCHAR(255) NOT NULL, current_state VARCHAR(255) NOT NULL, conversion_rate VARCHAR(255) NOT NULL, recyclable VARCHAR(255) NOT NULL, gift VARCHAR(255) NOT NULL, gift_message VARCHAR(255) NOT NULL, tracking_number VARCHAR(255) NOT NULL, total_discounts VARCHAR(255) NOT NULL, total_discounts_tax_incl VARCHAR(255) NOT NULL, total_discounts_tax_excl VARCHAR(255) NOT NULL, total_paid VARCHAR(255) NOT NULL, total_paid_tax_incl VARCHAR(255) NOT NULL, total_paid_tax_excl VARCHAR(255) NOT NULL, total_paid_real VARCHAR(255) NOT NULL, total_beaty_cost VARCHAR(255) NOT NULL, date_add DATETIME NOT NULL, date_upd VARCHAR(255) NOT NULL, valid INT NOT NULL, deleted INT NOT NULL, reservation_no VARCHAR(255) NOT NULL, reservation_approved INT NOT NULL, deployment_status INT NOT NULL, beaty_notes VARCHAR(255) NOT NULL, payment VARCHAR(255) NOT NULL, module VARCHAR(255) NOT NULL, order_note VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE services (id INT AUTO_INCREMENT NOT NULL, service_descriptions_id INT DEFAULT NULL, model VARCHAR(255) NOT NULL, sku VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, quantity INT NOT NULL, stock_status_id INT NOT NULL, manufacturer_id INT NOT NULL, shipping TINYINT(1) NOT NULL, ship_individually TINYINT(1) NOT NULL, free_shipping TINYINT(1) NOT NULL, shipping_price NUMERIC(10, 0) NOT NULL, price NUMERIC(10, 0) NOT NULL, tax_class_id INT NOT NULL, date_available DATETIME NOT NULL, weight NUMERIC(10, 0) NOT NULL, weight_class_id INT NOT NULL, lenght NUMERIC(10, 0) NOT NULL, width NUMERIC(10, 0) NOT NULL, height NUMERIC(10, 0) NOT NULL, lenght_class_id INT NOT NULL, status TINYINT(1) NOT NULL, viewed INT NOT NULL, sort_order INT NOT NULL, subtract TINYINT(1) NOT NULL, minimum INT NOT NULL, maximum INT NOT NULL, cost NUMERIC(10, 0) NOT NULL, call_to_order TINYINT(1) NOT NULL, settings VARCHAR(255) NOT NULL, date_added DATETIME NOT NULL, date_modified DATETIME NOT NULL, services_featured VARCHAR(255) NOT NULL, services_related VARCHAR(255) NOT NULL, services_to_categories VARCHAR(255) NOT NULL, services_to_downloads VARCHAR(255) NOT NULL, services_to_stores VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_7332E1691F1DEA87 (service_descriptions_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disk_jockey_orders (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, characteristics VARCHAR(255) NOT NULL, featured_image VARCHAR(255) NOT NULL, featured_video VARCHAR(255) NOT NULL, currency VARCHAR(255) NOT NULL, class VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_filter_ranges_descriptions (id INT AUTO_INCREMENT NOT NULL, range_id INT NOT NULL, name VARCHAR(255) NOT NULL, lang_id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL, subtype VARCHAR(255) NOT NULL, level VARCHAR(255) NOT NULL, visibility VARCHAR(255) NOT NULL, text VARCHAR(255) NOT NULL, association_type VARCHAR(255) NOT NULL, association_id INT NOT NULL, user VARCHAR(255) NOT NULL, timestamp DATETIME NOT NULL, date_upd DATETIME NOT NULL, important TINYINT(1) NOT NULL, sticky TINYINT(1) NOT NULL, color VARCHAR(255) NOT NULL, font_color VARCHAR(255) NOT NULL, link_color VARCHAR(255) NOT NULL, location_id INT NOT NULL, record_links VARCHAR(255) NOT NULL, eventData INT DEFAULT NULL, UNIQUE INDEX UNIQ_5387574A51658074 (eventData), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_cr_orders (id INT AUTO_INCREMENT NOT NULL, eventcr_id INT NOT NULL, prop_exp INT NOT NULL, customer_id INT NOT NULL, vendor_id INT NOT NULL, party_id INT NOT NULL, id_currency VARCHAR(255) NOT NULL, reference VARCHAR(255) NOT NULL, current_state INT NOT NULL, conversion_rate NUMERIC(10, 0) NOT NULL, recyclable INT NOT NULL, gift VARCHAR(255) NOT NULL, gift_message VARCHAR(255) NOT NULL, tracking_number VARCHAR(255) NOT NULL, total_discounts_tax_excl NUMERIC(10, 0) NOT NULL, total_discounts VARCHAR(255) NOT NULL, total_discounts_tax_incl VARCHAR(255) NOT NULL, total_paid NUMERIC(10, 0) NOT NULL, total_paid_tax_icl NUMERIC(10, 0) NOT NULL, total_paid_tax_excl NUMERIC(10, 0) NOT NULL, total_paid_real NUMERIC(10, 0) NOT NULL, total_eventcr VARCHAR(255) NOT NULL, order_date DATETIME NOT NULL, valid VARCHAR(255) NOT NULL, date_add VARCHAR(255) NOT NULL, date_upd VARCHAR(255) NOT NULL, deleted VARCHAR(255) NOT NULL, reservation_date VARCHAR(255) NOT NULL, reservation_no VARCHAR(255) NOT NULL, reservation_approved INT NOT NULL, deployment_date DATETIME NOT NULL, deployment_status NUMERIC(10, 0) NOT NULL, order_note VARCHAR(255) NOT NULL, payment VARCHAR(255) NOT NULL, module VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refresh_token (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_C74F21955F37A13B (token), INDEX IDX_C74F219519EB6921 (client_id), INDEX IDX_C74F2195A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE delivery (id INT AUTO_INCREMENT NOT NULL, id_vendor VARCHAR(255) NOT NULL, id_vendor_group VARCHAR(255) NOT NULL, id_carrier VARCHAR(255) NOT NULL, id_range_price VARCHAR(255) NOT NULL, id_range_weight VARCHAR(255) NOT NULL, id_zone VARCHAR(255) NOT NULL, price VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE risk (id INT AUTO_INCREMENT NOT NULL, percent VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, lang VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE access_token ADD CONSTRAINT FK_B6A2DD6819EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE access_token ADD CONSTRAINT FK_B6A2DD689B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE vendor ADD CONSTRAINT FK_F52233F65CAE469F FOREIGN KEY (vendorDescriptions) REFERENCES vendor_descriptons (id)');
        $this->addSql('ALTER TABLE vendor ADD CONSTRAINT FK_F52233F69B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE service_campaigns ADD CONSTRAINT FK_BBE24E3AED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_campaigns ADD CONSTRAINT FK_BBE24E3AB0EF31F7 FOREIGN KEY (campaigns_id) REFERENCES campaigns (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tax_rates ADD CONSTRAINT FK_F7AE5E1D3F3A0FD9 FOREIGN KEY (taxRateDescriptions) REFERENCES tax_rate_descriptions (id)');
        $this->addSql('ALTER TABLE tax_classes ADD CONSTRAINT FK_43A5DECFBC6DC00D FOREIGN KEY (taxClassDescriptions) REFERENCES tax_class_descriptions (id)');
        $this->addSql('ALTER TABLE auth_code ADD CONSTRAINT FK_5933D02C19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE auth_code ADD CONSTRAINT FK_5933D02CA76ED395 FOREIGN KEY (user_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE campaign_attachments ADD CONSTRAINT FK_9F0EC62CF639F774 FOREIGN KEY (campaign_id) REFERENCES campaigns (id)');
        $this->addSql('ALTER TABLE live_parties ADD CONSTRAINT FK_C2BE587E9B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE live_parties ADD CONSTRAINT FK_C2BE587EF603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor (id)');
        $this->addSql('ALTER TABLE live_parties ADD CONSTRAINT FK_C2BE587E6D1D6203 FOREIGN KEY (vendorGroup_id) REFERENCES vendor_groups (id)');
        $this->addSql('ALTER TABLE party ADD CONSTRAINT FK_89954EE0D96A31F1 FOREIGN KEY (zone_id_id) REFERENCES zone (id)');
        $this->addSql('ALTER TABLE order_data ADD CONSTRAINT FK_E002C974335238BF FOREIGN KEY (orderDataTypes) REFERENCES order_data_types (id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CF639F774 FOREIGN KEY (campaign_id) REFERENCES campaigns (id)');
        $this->addSql('ALTER TABLE agency ADD CONSTRAINT FK_70C0C6E69B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE service_option_values ADD CONSTRAINT FK_A948F4B318C90441 FOREIGN KEY (serviceOptionValueDescriptions) REFERENCES service_option_value_descriptions (id)');
        $this->addSql('ALTER TABLE aso_ebi ADD CONSTRAINT FK_98AEC13AA23B42D FOREIGN KEY (manufacturer_id) REFERENCES manufacturers (id)');
        $this->addSql('ALTER TABLE aso_ebi ADD CONSTRAINT FK_98AEC13AF603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor (id)');
        $this->addSql('ALTER TABLE aso_ebi ADD CONSTRAINT FK_98AEC13A9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id)');
        $this->addSql('ALTER TABLE services ADD CONSTRAINT FK_7332E1691F1DEA87 FOREIGN KEY (service_descriptions_id) REFERENCES service_descriptions (id)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574A51658074 FOREIGN KEY (eventData) REFERENCES events_data (id)');
        $this->addSql('ALTER TABLE refresh_token ADD CONSTRAINT FK_C74F219519EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE refresh_token ADD CONSTRAINT FK_C74F2195A76ED395 FOREIGN KEY (user_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE order_data_types CHANGE name name VARCHAR(255) NOT NULL, CHANGE date_add date_add VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE accounts CHANGE slug slug VARCHAR(255) DEFAULT NULL, CHANGE facebook_id facebook_id VARCHAR(255) DEFAULT NULL, CHANGE facebook_access_token facebook_access_token VARCHAR(255) DEFAULT NULL, CHANGE google_id google_id VARCHAR(255) DEFAULT NULL, CHANGE google_access_token google_access_token VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE accounts ADD CONSTRAINT FK_CAC89EAC932B1E0 FOREIGN KEY (account_detail) REFERENCES account_details (id)');
        $this->addSql('ALTER TABLE tax CHANGE rate rate VARCHAR(255) NOT NULL, CHANGE active active VARCHAR(255) NOT NULL, CHANGE deleted deleted VARCHAR(255) NOT NULL, CHANGE lang lang VARCHAR(255) NOT NULL, CHANGE rule rule VARCHAR(255) NOT NULL, CHANGE rules_group rules_group VARCHAR(255) NOT NULL, CHANGE rules_group_vendor rules_group_vendor VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE tax_rate_descriptions CHANGE description description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE advice CHANGE id_ps_advice id_ps_advice VARCHAR(255) NOT NULL, CHANGE id_tab id_tab VARCHAR(255) NOT NULL, CHANGE validated validated VARCHAR(255) NOT NULL, CHANGE ids_tab ids_tab VARCHAR(255) NOT NULL, CHANGE hide hide VARCHAR(255) NOT NULL, CHANGE location location VARCHAR(255) NOT NULL, CHANGE selector selector VARCHAR(255) NOT NULL, CHANGE start_day start_day VARCHAR(255) NOT NULL, CHANGE stop_day stop_day VARCHAR(255) NOT NULL, CHANGE weight weight VARCHAR(255) NOT NULL, CHANGE user_group user_group VARCHAR(255) NOT NULL, CHANGE language language VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE supplier CHANGE name name VARCHAR(255) NOT NULL, CHANGE date_add date_add VARCHAR(255) NOT NULL, CHANGE date_upd date_upd VARCHAR(255) NOT NULL, CHANGE active active VARCHAR(255) NOT NULL, CHANGE deleted deleted VARCHAR(255) NOT NULL, CHANGE lang lang VARCHAR(255) NOT NULL, CHANGE shop shop VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE order_download CHANGE name name VARCHAR(255) NOT NULL, CHANGE filename filename VARCHAR(255) NOT NULL, CHANGE mask mask VARCHAR(255) NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE sort_order sort_order VARCHAR(255) NOT NULL, CHANGE activate activate VARCHAR(255) NOT NULL, CHANGE attributes_data attributes_data VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE order_totals CHANGE title title VARCHAR(255) NOT NULL, CHANGE text text VARCHAR(255) NOT NULL, CHANGE type type VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE campaigns CHANGE slug slug VARCHAR(255) NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE assigned_to assigned_to VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) NOT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE cost cost VARCHAR(255) NOT NULL, CHANGE template template VARCHAR(255) NOT NULL, CHANGE subject subject VARCHAR(255) NOT NULL, CHANGE content content VARCHAR(255) NOT NULL, CHANGE created_by created_by VARCHAR(255) NOT NULL, CHANGE updated_by updated_by VARCHAR(255) NOT NULL, CHANGE send_as send_as VARCHAR(255) NOT NULL, CHANGE enable_redirect_links enable_redirect_links VARCHAR(255) NOT NULL, CHANGE open_rate open_rate VARCHAR(255) NOT NULL, CHANGE click_rate click_rate VARCHAR(255) NOT NULL, CHANGE unsubscribe_rate unsubscribe_rate VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE campaigns ADD CONSTRAINT FK_E3737470AC9C95FD FOREIGN KEY (image_url) REFERENCES media (id)');
        $this->addSql('ALTER TABLE affiliates CHANGE name name VARCHAR(255) NOT NULL, CHANGE mnemonic mnemonic VARCHAR(255) NOT NULL, CHANGE comments comments VARCHAR(255) NOT NULL, CHANGE contact contact VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE website website VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE affiliates ADD CONSTRAINT FK_108C6A8FCDEADB2A FOREIGN KEY (agency_id) REFERENCES agency (id)');
        $this->addSql('ALTER TABLE affiliates ADD CONSTRAINT FK_108C6A8F9B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE affiliates ADD CONSTRAINT FK_108C6A8F493EE2F0 FOREIGN KEY (affiliatesExtra) REFERENCES affiliates_extra (id)');
        $this->addSql('ALTER TABLE lighting_and_sound_orders CHANGE category category VARCHAR(255) NOT NULL, CHANGE class class VARCHAR(255) NOT NULL, CHANGE notes notes VARCHAR(255) NOT NULL, CHANGE ls_notes ls_notes VARCHAR(255) NOT NULL, CHANGE hall_size hall_size VARCHAR(255) NOT NULL, CHANGE capacity capacity VARCHAR(255) NOT NULL, CHANGE id_currency id_currency VARCHAR(255) NOT NULL, CHANGE reference reference VARCHAR(255) NOT NULL, CHANGE current_state current_state VARCHAR(255) NOT NULL, CHANGE conversion_rate conversion_rate VARCHAR(255) NOT NULL, CHANGE recyclable recyclable VARCHAR(255) NOT NULL, CHANGE gift gift VARCHAR(255) NOT NULL, CHANGE gift_notes gift_notes VARCHAR(255) NOT NULL, CHANGE tracking_number tracking_number VARCHAR(255) NOT NULL, CHANGE total_discounts total_discounts VARCHAR(255) NOT NULL, CHANGE total_discounts_tax_incl total_discounts_tax_incl VARCHAR(255) NOT NULL, CHANGE total_discounts_tax_excl total_discounts_tax_excl VARCHAR(255) NOT NULL, CHANGE total_paid total_paid VARCHAR(255) NOT NULL, CHANGE total_paid_tax_incl total_paid_tax_incl VARCHAR(255) NOT NULL, CHANGE total_paid_tax_excl total_paid_tax_excl VARCHAR(255) NOT NULL, CHANGE total_paid_real total_paid_real VARCHAR(255) NOT NULL, CHANGE total_ls_cost total_ls_cost VARCHAR(255) NOT NULL, CHANGE valid valid VARCHAR(255) NOT NULL, CHANGE deleted deleted VARCHAR(255) NOT NULL, CHANGE date_upd date_upd VARCHAR(255) NOT NULL, CHANGE reservation_no reservation_no VARCHAR(255) NOT NULL, CHANGE reservation_date reservation_date VARCHAR(255) NOT NULL, CHANGE reservation_approved reservation_approved VARCHAR(255) NOT NULL, CHANGE deployment_date deployment_date VARCHAR(255) NOT NULL, CHANGE deployment_status deployment_status VARCHAR(255) NOT NULL, CHANGE payment payment VARCHAR(255) NOT NULL, CHANGE module module VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE tax_class_descriptions CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE service_option_descriptions CHANGE name name VARCHAR(255) NOT NULL, CHANGE option_placeholder option_placeholder VARCHAR(255) NOT NULL, CHANGE error_text error_text VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE order_statuses CHANGE name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE order_options CHANGE name name VARCHAR(255) NOT NULL, CHANGE sku sku VARCHAR(255) NOT NULL, CHANGE value value VARCHAR(255) NOT NULL, CHANGE prefix prefix VARCHAR(255) NOT NULL, CHANGE settings settings VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE order_download_history CHANGE filename filename VARCHAR(255) NOT NULL, CHANGE mask mask VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE order_download_history ADD CONSTRAINT FK_E9D26592EF0098DE FOREIGN KEY (orderDownloadHistory) REFERENCES order_download (id)');
        $this->addSql('ALTER TABLE mail CHANGE recipient recipient VARCHAR(255) NOT NULL, CHANGE template template VARCHAR(255) NOT NULL, CHANGE subject subject VARCHAR(255) NOT NULL, CHANGE id_lang id_lang VARCHAR(255) NOT NULL, CHANGE date_add date_add VARCHAR(255) NOT NULL, CHANGE date_upd date_upd VARCHAR(255) NOT NULL, CHANGE deleted deleted VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE state CHANGE id_country id_country VARCHAR(255) NOT NULL, CHANGE id_zone id_zone VARCHAR(255) NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE iso_code iso_code VARCHAR(255) NOT NULL, CHANGE tax_behavior tax_behavior VARCHAR(255) NOT NULL, CHANGE active active VARCHAR(255) NOT NULL, CHANGE deleted deleted VARCHAR(255) NOT NULL, CHANGE date_add date_add VARCHAR(255) NOT NULL, CHANGE date_upd date_upd VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE address CHANGE id_state id_state VARCHAR(255) NOT NULL, CHANGE id_manufacturer id_manufacturer VARCHAR(255) NOT NULL, CHANGE id_supplier id_supplier VARCHAR(255) NOT NULL, CHANGE id_warehouse id_warehouse VARCHAR(255) NOT NULL, CHANGE alias alias VARCHAR(255) NOT NULL, CHANGE company company VARCHAR(255) NOT NULL, CHANGE address1 address1 VARCHAR(255) NOT NULL, CHANGE address2 address2 VARCHAR(255) NOT NULL, CHANGE postcode postcode VARCHAR(255) NOT NULL, CHANGE city city VARCHAR(255) NOT NULL, CHANGE other other VARCHAR(255) NOT NULL, CHANGE phone phone VARCHAR(255) NOT NULL, CHANGE phone_number phone_number VARCHAR(255) NOT NULL, CHANGE vat_number vat_number VARCHAR(255) NOT NULL, CHANGE date_add date_add VARCHAR(255) NOT NULL, CHANGE date_upd date_upd VARCHAR(255) NOT NULL, CHANGE active active VARCHAR(255) NOT NULL, CHANGE deleted deleted VARCHAR(255) NOT NULL, CHANGE suspende suspende VARCHAR(255) NOT NULL, CHANGE format format VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F819B6B5FBA FOREIGN KEY (account_id) REFERENCES account_details (id)');
        $this->addSql('ALTER TABLE warehouse CHANGE id_currency id_currency VARCHAR(255) NOT NULL, CHANGE id_address id_address VARCHAR(255) NOT NULL, CHANGE id_employee id_employee VARCHAR(255) NOT NULL, CHANGE reference reference VARCHAR(255) NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE management_type management_type VARCHAR(255) NOT NULL, CHANGE deleted deleted VARCHAR(255) NOT NULL, CHANGE active active VARCHAR(255) NOT NULL, CHANGE carrier carrier VARCHAR(255) NOT NULL, CHANGE product_location product_location VARCHAR(255) NOT NULL, CHANGE vendor vendor VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE files CHANGE filename filename VARCHAR(255) NOT NULL, CHANGE contents contents VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE service_filter_ranges CHANGE form form VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE vendor_descriptons CHANGE description description VARCHAR(255) NOT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE meta_description meta_description VARCHAR(255) NOT NULL, CHANGE meta_keywords meta_keywords VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE order_status_ids CHANGE status_text_id status_text_id VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE service_options CHANGE element_type element_type VARCHAR(255) NOT NULL, CHANGE regexp_pattern regexp_pattern VARCHAR(255) NOT NULL, CHANGE settings settings VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE service_options ADD CONSTRAINT FK_1FB1A81B5222F501 FOREIGN KEY (serviceOptionDescriptions) REFERENCES service_option_descriptions (id)');
        $this->addSql('ALTER TABLE search_word CHANGE id_service id_service VARCHAR(255) NOT NULL, CHANGE id_lang id_lang VARCHAR(255) NOT NULL, CHANGE word word VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE security CHANGE class class VARCHAR(255) NOT NULL, CHANGE category category VARCHAR(255) NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE featured_image featured_image VARCHAR(255) NOT NULL, CHANGE featured_video featured_video VARCHAR(255) NOT NULL, CHANGE documentaries documentaries VARCHAR(255) NOT NULL, CHANGE tags tags VARCHAR(255) NOT NULL, CHANGE meta_title meta_title VARCHAR(255) NOT NULL, CHANGE meta_description meta_description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE service_tags CHANGE tag tag VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE affiliates_extra CHANGE address address VARCHAR(255) NOT NULL, CHANGE city city VARCHAR(255) NOT NULL, CHANGE postcode postcode VARCHAR(255) NOT NULL, CHANGE country country VARCHAR(255) NOT NULL, CHANGE phone phone VARCHAR(255) NOT NULL, CHANGE fax fax VARCHAR(255) NOT NULL, CHANGE account_type account_type VARCHAR(255) NOT NULL, CHANGE account_contact account_contact VARCHAR(255) NOT NULL, CHANGE payee_name payee_name VARCHAR(255) NOT NULL, CHANGE mode_of_payment mode_of_payment VARCHAR(255) NOT NULL, CHANGE category category VARCHAR(255) NOT NULL, CHANGE help_file help_file VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE category CHANGE name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1727ACA70 FOREIGN KEY (parent_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE zone CHANGE name name VARCHAR(255) NOT NULL, CHANGE active active VARCHAR(255) NOT NULL, CHANGE deleted deleted VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE zone ADD CONSTRAINT FK_A0EBC0072FC8C4DB FOREIGN KEY (zoneDescriptions) REFERENCES zone_descriptions (id)');
        $this->addSql('ALTER TABLE employee CHANGE id_profile id_profile VARCHAR(255) NOT NULL, CHANGE id_lang id_lang VARCHAR(255) NOT NULL, CHANGE lastname lastname VARCHAR(255) NOT NULL, CHANGE firstname firstname VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE passwd passwd VARCHAR(255) NOT NULL, CHANGE plain_pwd plain_pwd VARCHAR(255) NOT NULL, CHANGE last_pwd_gen last_pwd_gen VARCHAR(255) NOT NULL, CHANGE stats_date_from stats_date_from VARCHAR(255) NOT NULL, CHANGE stats_date_to stats_date_to VARCHAR(255) NOT NULL, CHANGE stats_compare_from stats_compare_from VARCHAR(255) NOT NULL, CHANGE stats_compare_to stats_compare_to VARCHAR(255) NOT NULL, CHANGE stats_compare_option stats_compare_option VARCHAR(255) NOT NULL, CHANGE preselect_date_range preselect_date_range VARCHAR(255) NOT NULL, CHANGE bo_color bo_color VARCHAR(255) NOT NULL, CHANGE active active VARCHAR(255) NOT NULL, CHANGE optin optin VARCHAR(255) NOT NULL, CHANGE id_last_order id_last_order VARCHAR(255) NOT NULL, CHANGE id_last_customer_message id_last_customer_message VARCHAR(255) NOT NULL, CHANGE id_last_customer id_last_customer VARCHAR(255) NOT NULL, CHANGE last_connection_date last_connection_date VARCHAR(255) NOT NULL, CHANGE vendor vendor VARCHAR(255) NOT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE services DROP FOREIGN KEY FK_7332E1691F1DEA87');
        $this->addSql('ALTER TABLE live_parties DROP FOREIGN KEY FK_C2BE587EF603EE73');
        $this->addSql('ALTER TABLE aso_ebi DROP FOREIGN KEY FK_98AEC13AF603EE73');
        $this->addSql('ALTER TABLE service_campaigns DROP FOREIGN KEY FK_BBE24E3AED5CA9E6');
        $this->addSql('ALTER TABLE zone DROP FOREIGN KEY FK_A0EBC0072FC8C4DB');
        $this->addSql('ALTER TABLE service_option_values DROP FOREIGN KEY FK_A948F4B318C90441');
        $this->addSql('ALTER TABLE live_parties DROP FOREIGN KEY FK_C2BE587E6D1D6203');
        $this->addSql('ALTER TABLE campaigns DROP FOREIGN KEY FK_E3737470AC9C95FD');
        $this->addSql('ALTER TABLE aso_ebi DROP FOREIGN KEY FK_98AEC13AA23B42D');
        $this->addSql('ALTER TABLE affiliates DROP FOREIGN KEY FK_108C6A8FCDEADB2A');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY FK_5387574A51658074');
        $this->addSql('ALTER TABLE accounts DROP FOREIGN KEY FK_CAC89EAC932B1E0');
        $this->addSql('ALTER TABLE address DROP FOREIGN KEY FK_D4E6F819B6B5FBA');
        $this->addSql('DROP TABLE access_token');
        $this->addSql('DROP TABLE gender');
        $this->addSql('DROP TABLE billing_categories');
        $this->addSql('DROP TABLE transport_orders');
        $this->addSql('DROP TABLE service_descriptions');
        $this->addSql('DROP TABLE event_invitations');
        $this->addSql('DROP TABLE vendor');
        $this->addSql('DROP TABLE carrier');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE service_campaigns');
        $this->addSql('DROP TABLE zone_descriptions');
        $this->addSql('DROP TABLE stock');
        $this->addSql('DROP TABLE tax_rates');
        $this->addSql('DROP TABLE service_discounts');
        $this->addSql('DROP TABLE tax_classes');
        $this->addSql('DROP TABLE party_editor');
        $this->addSql('DROP TABLE specific_price');
        $this->addSql('DROP TABLE auth_code');
        $this->addSql('DROP TABLE food_orders');
        $this->addSql('DROP TABLE campaign_attachments');
        $this->addSql('DROP TABLE pre_registration');
        $this->addSql('DROP TABLE live_parties');
        $this->addSql('DROP TABLE order_services');
        $this->addSql('DROP TABLE party');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE order_data');
        $this->addSql('DROP TABLE order_history');
        $this->addSql('DROP TABLE customization');
        $this->addSql('DROP TABLE service_option_value_descriptions');
        $this->addSql('DROP TABLE services_filters');
        $this->addSql('DROP TABLE vendor_groups');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE manufacturers');
        $this->addSql('DROP TABLE tags');
        $this->addSql('DROP TABLE janitorial_services_orders');
        $this->addSql('DROP TABLE imports');
        $this->addSql('DROP TABLE mc_orders');
        $this->addSql('DROP TABLE links');
        $this->addSql('DROP TABLE service_filter_discriptions');
        $this->addSql('DROP TABLE operating_system');
        $this->addSql('DROP TABLE service_specials');
        $this->addSql('DROP TABLE mixologist_orders');
        $this->addSql('DROP TABLE agency');
        $this->addSql('DROP TABLE service_option_values');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE drink_order');
        $this->addSql('DROP TABLE event_center');
        $this->addSql('DROP TABLE supply_order');
        $this->addSql('DROP TABLE posts');
        $this->addSql('DROP TABLE bug_reports');
        $this->addSql('DROP TABLE aso_ebi');
        $this->addSql('DROP TABLE events_data');
        $this->addSql('DROP TABLE account_details');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE beauty_and_makeup_orders');
        $this->addSql('DROP TABLE services');
        $this->addSql('DROP TABLE disk_jockey_orders');
        $this->addSql('DROP TABLE service_filter_ranges_descriptions');
        $this->addSql('DROP TABLE events');
        $this->addSql('DROP TABLE event_cr_orders');
        $this->addSql('DROP TABLE refresh_token');
        $this->addSql('DROP TABLE delivery');
        $this->addSql('DROP TABLE risk');
        $this->addSql('ALTER TABLE accounts CHANGE slug slug VARCHAR(180) DEFAULT NULL COLLATE utf8mb4_unicode_ci, CHANGE facebook_id facebook_id VARCHAR(180) DEFAULT NULL COLLATE utf8mb4_unicode_ci, CHANGE facebook_access_token facebook_access_token VARCHAR(180) DEFAULT NULL COLLATE utf8mb4_unicode_ci, CHANGE google_id google_id VARCHAR(180) DEFAULT NULL COLLATE utf8mb4_unicode_ci, CHANGE google_access_token google_access_token VARCHAR(180) DEFAULT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE address CHANGE id_state id_state VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_manufacturer id_manufacturer VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_supplier id_supplier VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_warehouse id_warehouse VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE alias alias VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE company company VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE address1 address1 VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE address2 address2 VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE postcode postcode VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE city city VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE other other VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE phone phone VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE phone_number phone_number VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE vat_number vat_number VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE date_add date_add VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE date_upd date_upd VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE active active VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE deleted deleted VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE suspende suspende VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE format format VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE advice CHANGE id_ps_advice id_ps_advice VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_tab id_tab VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE validated validated VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE ids_tab ids_tab VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE hide hide VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE location location VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE selector selector VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE start_day start_day VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE stop_day stop_day VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE weight weight VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE user_group user_group VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE language language VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE affiliates DROP FOREIGN KEY FK_108C6A8F9B6B5FBA');
        $this->addSql('ALTER TABLE affiliates DROP FOREIGN KEY FK_108C6A8F493EE2F0');
        $this->addSql('ALTER TABLE affiliates CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE mnemonic mnemonic VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE comments comments VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE contact contact VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE email email VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE website website VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE affiliates_extra CHANGE address address VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE city city VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE postcode postcode VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE country country VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE phone phone VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE fax fax VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE account_type account_type VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE account_contact account_contact VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE payee_name payee_name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE mode_of_payment mode_of_payment VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE category category VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE help_file help_file VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE campaigns CHANGE slug slug VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE assigned_to assigned_to VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE description description VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE type type VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE cost cost VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE template template VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE subject subject VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE content content VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE created_by created_by VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE updated_by updated_by VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE send_as send_as VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE enable_redirect_links enable_redirect_links VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE open_rate open_rate VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE click_rate click_rate VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE unsubscribe_rate unsubscribe_rate VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1727ACA70');
        $this->addSql('ALTER TABLE category CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE employee CHANGE id_profile id_profile VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_lang id_lang VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE lastname lastname VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE firstname firstname VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE email email VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE passwd passwd VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE plain_pwd plain_pwd VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE last_pwd_gen last_pwd_gen VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE stats_date_from stats_date_from VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE stats_date_to stats_date_to VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE stats_compare_from stats_compare_from VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE stats_compare_to stats_compare_to VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE stats_compare_option stats_compare_option VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE preselect_date_range preselect_date_range VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE bo_color bo_color VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE active active VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE optin optin VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_last_order id_last_order VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_last_customer_message id_last_customer_message VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_last_customer id_last_customer VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE last_connection_date last_connection_date VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE vendor vendor VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE files CHANGE filename filename VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE contents contents VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE lighting_and_sound_orders CHANGE category category VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE class class VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE notes notes VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE ls_notes ls_notes VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE hall_size hall_size VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE capacity capacity VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_currency id_currency VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE reference reference VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE current_state current_state VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE conversion_rate conversion_rate VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE recyclable recyclable VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE gift gift VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE gift_notes gift_notes VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE tracking_number tracking_number VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE total_discounts total_discounts VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE total_discounts_tax_incl total_discounts_tax_incl VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE total_discounts_tax_excl total_discounts_tax_excl VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE total_paid total_paid VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE total_paid_tax_incl total_paid_tax_incl VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE total_paid_tax_excl total_paid_tax_excl VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE total_paid_real total_paid_real VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE total_ls_cost total_ls_cost VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE valid valid VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE deleted deleted VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE date_upd date_upd VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE reservation_no reservation_no VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE reservation_date reservation_date VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE reservation_approved reservation_approved VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE deployment_date deployment_date VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE deployment_status deployment_status VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE payment payment VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE module module VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE mail CHANGE recipient recipient VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE template template VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE subject subject VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_lang id_lang VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE date_add date_add VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE date_upd date_upd VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE deleted deleted VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE order_data_types CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE date_add date_add VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE order_download CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE filename filename VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE mask mask VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE status status VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE sort_order sort_order VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE activate activate VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE attributes_data attributes_data VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE order_download_history DROP FOREIGN KEY FK_E9D26592EF0098DE');
        $this->addSql('ALTER TABLE order_download_history CHANGE filename filename VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE mask mask VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE order_options CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE sku sku VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE value value VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE prefix prefix VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE settings settings VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE order_status_ids CHANGE status_text_id status_text_id VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE order_statuses CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE order_totals CHANGE title title VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE text text VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE type type VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE search_word CHANGE id_service id_service VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_lang id_lang VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE word word VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE security CHANGE class class VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE category category VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE featured_image featured_image VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE featured_video featured_video VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE documentaries documentaries VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE tags tags VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE meta_title meta_title VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE meta_description meta_description VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE service_filter_ranges CHANGE form form VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE service_option_descriptions CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE option_placeholder option_placeholder VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE error_text error_text VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE service_options DROP FOREIGN KEY FK_1FB1A81B5222F501');
        $this->addSql('ALTER TABLE service_options CHANGE element_type element_type VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE regexp_pattern regexp_pattern VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE settings settings VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE service_tags CHANGE tag tag VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE state CHANGE id_country id_country VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_zone id_zone VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE iso_code iso_code VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE tax_behavior tax_behavior VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE active active VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE deleted deleted VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE date_add date_add VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE date_upd date_upd VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE supplier CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE date_add date_add VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE date_upd date_upd VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE active active VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE deleted deleted VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE lang lang VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shop shop VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE tax CHANGE rate rate VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE active active VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE deleted deleted VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE lang lang VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE rule rule VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE rules_group rules_group VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE rules_group_vendor rules_group_vendor VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE tax_class_descriptions CHANGE title title VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE description description VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE tax_rate_descriptions CHANGE description description VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE vendor_descriptons CHANGE description description VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE title title VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE meta_description meta_description VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE meta_keywords meta_keywords VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE warehouse CHANGE id_currency id_currency VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_address id_address VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE id_employee id_employee VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE reference reference VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE management_type management_type VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE deleted deleted VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE active active VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE carrier carrier VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE product_location product_location VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE vendor vendor VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE zone CHANGE name name VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE active active VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE deleted deleted VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci');
    }
}
