runtime: php
service: default
env: flex

runtime_config:
  document_root: web
  front_controller_file: app.php
  composer_flags: --no-dev --optimize-autoloader
  nginx_conf_include: nginx-app.conf
  supervisord_conf_addition: additional-supervisord.conf
  php_ini_override: php.ini
  nginx_conf_http_include: nginx-http.conf

# [START overrides]
env_variables:
  SYMFONY_ENV: prod
  DB_DATABASE: symfony
  DB_USERNAME: root
  DB_PASSWORD: lBheKJbuHBJmIOK1
  DB_HOST: 35.198.90.159
  DB_PORT : 3306
# [END overrides]

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1000
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.8

resources:
  cpu: 0.5
  memory_gb: 0.6
  disk_size_gb: 10