service: default
runtime: php
env: flex

# [START entrypoint]
entrypoint: ppm/bin/ppm start --bootstrap=symfony --app-env=prod --debug=0 --concurrent-requests=1
# [END entrypoint]

runtime_config:
  document_root: web
  nginx_conf_include: nginx-app.conf
  composer_flags: --no-dev --optimize-autoloader

# [START overrides]
env_variables:
  SYMFONY_ENV: prod
# [END overrides]

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1000
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.8

resources:
  cpu: 0.5
  memory_gb: 0.5
  disk_size_gb: 10
