runtime: php
service: default
env: flex

runtime_config:
  document_root: web
  front_controller_file: app.php
  composer_flags: --no-dev --optimize-autoloader
  whitelist_functions: proc_open, proc_close

# [START overrides]
env_variables:
  SYMFONY_ENV: prod
  DB_DATABASE: symfony
  DB_USERNAME: root
  DB_PASSWORD: lBheKJbuHBJmIOK1
  DB_HOST: 35.198.90.159
  DB_PORT : 3306
# [END overrides]

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1000
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.3

resources:
  cpu: 0.5
