service: default
runtime: php
env: flex

# [START entrypoint]
entrypoint: php php-pm/bin/ppm start --bootstrap=symfony --port=8081 --app-env=prod --cgi-path=/usr/bin/php --debug=0 --concurrent-requests=1
# [END entrypoint]

runtime_config:
  document_root: web
  #front_controller_file: app.php
  nginx_conf_include: nginx-app.conf
  composer_flags: --no-dev --optimize-autoloader
  whitelist_functions: proc_open, proc_close

# [START overrides]
env_variables:
  SYMFONY_ENV: prod
# [END overrides]

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1000
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.8

#manual_scaling:
  #instances: 1

resources:
  cpu: 0.5
  memory_gb: 0.5
  disk_size_gb: 10
