runtime: php
env: flex
service: default

# [START entrypoint]
entrypoint: php php-pm/bin/ppm start --bootstrap=symfony --port=$PORT --app-env=prod --cgi-path=/usr/bin/php --debug=0 --concurrent-requests=1
# [END entrypoint]
runtime_config:
  document_root: web
  #front_controller_file: app.php
  composer_flags: --no-dev --optimize-autoloader
  whitelist_functions: proc_open, proc_close

# [START overrides]
env_variables:
  NGINX_CONF_INCLUDE: nginx-app.conf
  FRONT_CONTROLLER_FILE: ''
  SYMFONY_ENV: prod
  DB_DATABASE: symfony
  DB_USERNAME: root
  DB_PASSWORD: lBheKJbuHBJmIOK1
  DB_HOST: 35.198.90.159
# [END overrides]

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1000
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.8

#manual_scaling:
  #instances: 1

resources:
  cpu: 0.5
  memory_gb: 0.5
  disk_size_gb: 10
