#!/usr/bin/env bash

while [ 1 ]
do
    for ixx in $(seq 5500 5507); do

		(echo > /dev/tcp/127.0.0.1/${ixx}) >/dev/null 2>&1 && \
    	echo "It's up" || SERVERPORT=${ixx} php bin/server &

	done
    sleep 5
done
