<?php

namespace AppBundle\Repository;

/**
 * _GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class _GroupRepository extends \Doctrine\ORM\EntityRepository
{
}
