<?php

namespace AppBundle\Repository;

/**
 * _RangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class _RangeRepository extends \Doctrine\ORM\EntityRepository
{
}
