<?php

namespace AppBundle\Repository;

/**
 * AccessoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessoryRepository extends \Doctrine\ORM\EntityRepository
{
}
