<?php

namespace AppBundle\Repository;

/**
 * AffiliatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliatesRepository extends \Doctrine\ORM\EntityRepository
{
}
