<?php

namespace AppBundle\Repository;

/**
 * AffiliatesExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliatesExtraRepository extends \Doctrine\ORM\EntityRepository
{
}
