<?php

namespace AppBundle\Repository;

/**
 * ArtistesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistesOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
