<?php

namespace AppBundle\Repository;

/**
 * AsoEbiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsoEbiRepository extends \Doctrine\ORM\EntityRepository
{
}
