<?php

namespace AppBundle\Repository;

/**
 * BeautyAndMakeupOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeautyAndMakeupOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
