<?php

namespace AppBundle\Repository;

/**
 * BillingCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
