<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Repository;

/**
 * CampaignsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignsRepository extends \Doctrine\ORM\EntityRepository
{
    const MAX_HOME_CATEGORIES = 10;

    public function getHomeCampaigns(\AppBundle\Entity\Country $country): array
    {
        return $this->createQueryBuilder('p')
            ->where('p.isEnabled = true')
            ->andWhere('p.startDate <= :currentDate')
            ->andWhere('p.endDate >= :currentDate')
            ->setParameter('currentDate', new \DateTime('+1 day'))
            ->orderBy('p.endDate', 'ASC')
            ->setMaxResults(self::MAX_HOME_CATEGORIES)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getResult();
    }
}
