<?php

namespace AppBundle\Repository;

/**
 * CampaignsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getHomeCampaigns() :array
    {
        return $this->createQueryBuilder('p')
            ->where('p.isEnabled = true')
            ->andWhere('p.launchDate >= :currentDate')
            ->setParameter('currentDate', new \DateTime('now', new  \DateTimeZone('Africa/Lagos')))
            ->andWhere('p.dateEnd >= :currentDate')
            ->setParameter('currentDate', new \DateTime('now', new  \DateTimeZone('Africa/Lagos')))
            ->orderBy('p.dateEnd', 'DESC')
            ->setMaxResults(10)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getResult();
    }
}
