<?php

namespace AppBundle\Repository;

/**
 * CampaignsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignsRepository extends \Doctrine\ORM\EntityRepository
{
    const MAX_HOME_CATEGORIES = 10;

    public function getHomeCampaigns(\AppBundle\Entity\Country $country) :array
    {
        return $this->createQueryBuilder('p')
            ->where('p.isEnabled = true')
            ->andWhere('p.startDate <= :currentDate')
            ->andWhere('p.endDate >= :currentDate')
            ->setParameter('currentDate', (new \DateTime('now'))->setTimezone(new \DateTimeZone($country->getTimezone())))
            ->orderBy('p.endDate', 'ASC')
            ->setMaxResults(self::MAX_HOME_CATEGORIES)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getResult();
    }
}
