<?php

namespace AppBundle\Repository;

/**
 * CateringServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CateringServiceOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
