<?php

namespace AppBundle\Repository;

/**
 * ContactSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactSettingsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getContactSettings()
    {
        $em = $this->createQueryBuilder('p')
            ->select('p.contactName', 'p.contactAddress', 'p.contactPhone', 'p.contactAddress')
            ->where('p.contactEnabled = 1')
            ->getQuery();
        return $em->execute();
    }
}
