<?php

namespace AppBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName(string $name) : ?\AppBundle\Entity\Country
    {
        $hostname = parse_url($name)['host'];

        return $this->createQueryBuilder('p')
            ->where('p.isEnabled = true')
            ->andWhere('p.subdomain = :name')
            ->orWhere('p.hostname = :name')
            ->setParameter('name', $hostname)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getOneOrNullResult();
    }
}
