<?php

namespace AppBundle\Repository;

/**
 * CustomizerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomizerRepository extends \Doctrine\ORM\EntityRepository
{
}
