<?php

namespace AppBundle\Repository;

/**
 * CustomizedDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomizedDataRepository extends \Doctrine\ORM\EntityRepository
{
}
