<?php

namespace AppBundle\Repository;

/**
 * CustomizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomizationRepository extends \Doctrine\ORM\EntityRepository
{
}
