<?php

namespace AppBundle\Repository;

/**
 * DateRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
