<?php

namespace AppBundle\Repository;

/**
 * DecoratorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecoratorsOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
