<?php

namespace AppBundle\Repository;

/**
 * DiskJockeyOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiskJockeyOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
