<?php

namespace AppBundle\Repository;

/**
 * DrinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrinksRepository extends \Doctrine\ORM\EntityRepository
{
}
