<?php

namespace AppBundle\Repository;

/**
 * DrinkOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrinkOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
