<?php

namespace AppBundle\Repository;

/**
 * EventsDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsDataRepository extends \Doctrine\ORM\EntityRepository
{
}
