<?php

namespace AppBundle\Repository;

/**
 * EventCenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCenterRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllEventCenter()
    {
        $em = $this->createQueryBuilder('p')
            ->select('p.id', 'p.name, p.documentaries')
            ->where('p.language = 1')
            ->getQuery();
        return $em->execute();
    }
}
