<?php

namespace AppBundle\Repository;

/**
 * EventCenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCenterRepository extends \Doctrine\ORM\EntityRepository
{
}
