<?php

namespace AppBundle\Repository;

/**
 * EventCrOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCrOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
