<?php

namespace AppBundle\Repository;

/**
 * FoodOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
