<?php

namespace AppBundle\Repository;

/**
 * ImagingOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagingOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
