<?php

namespace AppBundle\Repository;

/**
 * JanitorialServicesOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JanitorialServicesOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
