<?php

namespace AppBundle\Repository;
use AppBundle\Entity\LandingPageSettings;

/**
 * LandingPageSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandingPageSettingsRepository extends \Doctrine\ORM\EntityRepository
{
    public function setAllSettings($w, $e, $r)
    {
        $allsettings = new LandingPageSettings();
        $allsettings->setIdContactsettings(2);
        $allsettings->setIdLinksettings(2);
        $allsettings->setIdSeosettings(2);

    }
}
