<?php

namespace AppBundle\Repository;

/**
 * LightingAndSoundOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LightingAndSoundOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
