<?php

namespace AppBundle\Repository;

/**
 * LivePartiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivePartiesRepository extends \Doctrine\ORM\EntityRepository
{
}
