<?php

namespace AppBundle\Repository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLocationByNameParent(string $location, $parent): ?\AppBundle\Entity\Location
    {
        return $this->createQueryBuilder('p')
            ->where('p.parent = :parent')
            ->andWhere('p.name LIKE :name')
            ->setParameter('name', $location)
            ->setParameter('parent', $parent)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getOneOrNullResult();
    }
}
