<?php

namespace AppBundle\Repository;

/**
 * McOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class McOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
