<?php

namespace AppBundle\Repository;

/**
 * MemcachedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemcachedRepository extends \Doctrine\ORM\EntityRepository
{
}
