<?php

namespace AppBundle\Repository;

/**
 * MixologistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MixologistOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
