<?php

namespace AppBundle\Repository;

/**
 * OrderOptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderOptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
