<?php

namespace AppBundle\Repository;

/**
 * OrderDownloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDownloadRepository extends \Doctrine\ORM\EntityRepository
{
}
