<?php

namespace AppBundle\Repository;

/**
 * OrderDownloadHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDownloadHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
