<?php

namespace AppBundle\Repository;

/**
 * OrderDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDataRepository extends \Doctrine\ORM\EntityRepository
{
}
