<?php

namespace AppBundle\Repository;

/**
 * OrderStatusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatusesRepository extends \Doctrine\ORM\EntityRepository
{
}
