<?php

namespace AppBundle\Repository;

/**
 * OrderStatusIdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatusIdsRepository extends \Doctrine\ORM\EntityRepository
{
}
