<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Pages;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCountry(string $slug) : ?Pages
    {
        return $this->createQueryBuilder('p')
            ->andWhere('p.isEnabled = true')
            ->andWhere('p.slug = :slug')
            ->setParameters($slug)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getOneOrNullResult();
    }
}
