<?php

namespace AppBundle\Repository;

/**
 * PageViewedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageViewedRepository extends \Doctrine\ORM\EntityRepository
{
}
