<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Country;
use AppBundle\Entity\Pages;

/**
 * PagesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySlug(string $slug): ?Pages
    {
        return $this->createQueryBuilder('p')
            ->andWhere('p.isEnabled = true')
            ->andWhere('p.slug = :slug')
            ->setParameters($slug)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getOneOrNullResult();
    }

    public function findAllByCountry(Country $country = null, int $page, $limit = self::NUM_ITEMS): Pagerfanta
    {
        $query = $this->createQueryBuilder('p')
                ->andWhere('p.isEnabled =  true')
                ->leftJoin('p.country', 'f')
                ->addSelect('f')
                ->andWhere('f = :country')
                ->setParameter('country', $country ?: !null)
                ->orderBy('p.created', 'DESC')
                ->getQuery()
                ->useQueryCache(true)
                ->useResultCache(true);

        return Sorter::createPaginator($query, $page, $limit);
    }
}
