<?php

namespace AppBundle\Repository;

/**
 * PageNotFoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageNotFoundRepository extends \Doctrine\ORM\EntityRepository
{
}
