<?php

namespace AppBundle\Repository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCountry(array $localisedSlug) : ?\AppBundle\Entity\Pages
    {
        return $this->createQueryBuilder('p')
            ->where('p.country = :country')
            ->andWhere('p.isEnabled = true')
            ->andWhere('p.slug = :slug')
            ->setParameters($localisedSlug)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getOneOrNullResult();
    }
}
