<?php

namespace AppBundle\Repository;

/**
 * PartyCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartyCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
