<?php

namespace AppBundle\Repository;

/**
 * PartyEditorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartyEditorRepository extends \Doctrine\ORM\EntityRepository
{
}
