<?php

namespace AppBundle\Repository;

/**
 * PartyUrlsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartyUrlsRepository extends \Doctrine\ORM\EntityRepository
{
}
