<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Service;

/**
 * PartyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartyRepository extends \Doctrine\ORM\EntityRepository
{
    const HOME_MAX_PARTIES = 6;

    public function findHomeParties(): array
    {
        return $this->createQueryBuilder('p')
            ->where('p.date >= :date')
            ->setParameter('date', new \DateTime('+ 2 days'))
            ->orderBy('p.created', 'DESC')
            ->setMaxResults(self::HOME_MAX_PARTIES)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getResult();
    }

    public function findPartiesByService(Service $service): array
    {
        return $this->createQueryBuilder('p')
            ->join('p.orders', 'm')
            ->addSelect('m')
            ->join('m.orderDatas', 'n')
            ->addSelect('n')
            ->where('n.service = :service')
            ->setParameter('service', $service)
            ->orderBy('p.created', 'DESC')
            ->setMaxResults(self::HOME_MAX_PARTIES)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
            ->getResult();
    }
}
