<?php

namespace AppBundle\Repository;

/**
 * PreRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreRegistrationRepository extends \Doctrine\ORM\EntityRepository
{
}
