<?php

namespace AppBundle\Repository;

/**
 * ReferrerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferrerRepository extends \Doctrine\ORM\EntityRepository
{
}
