<?php

namespace AppBundle\Repository;

/**
 * SearchWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchWordRepository extends \Doctrine\ORM\EntityRepository
{
}
