<?php

namespace AppBundle\Repository;

/**
 * SearchEngineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchEngineRepository extends \Doctrine\ORM\EntityRepository
{
}
