<?php

namespace AppBundle\Repository;

/**
 * SEKeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SEKeywordRepository extends \Doctrine\ORM\EntityRepository
{
}
