<?php

namespace AppBundle\Repository;

/**
 * serviceTagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceTagsRepository extends \Doctrine\ORM\EntityRepository
{
}
