<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    const NUM_ITEMS = 20;

    public function findBySearchQuery(
        string $rawQuery,
        string $category,
        \AppBundle\Entity\Country $country,
        int $page
    ): Pagerfanta {
        $searchTerms = \AppBundle\Utils\Sorter::buildTree(
            \AppBundle\Utils\Sorter::sanitizeString(
                $rawQuery
                )
            );
        $queryBuilder = $this->createQueryBuilder('p')
                ->where('f.title = :category')
                ->setParameter('category', $category)
                ->andWhere('f.country = :country')
                ->setParameter('country', $country);

        foreach ($searchTerms as $key => $term) {
            $queryBuilder
                ->orWhere('p.name LIKE :t_'.$key)
                ->setParameter('t_'.$key, '%'.$term.'%');
        }
        $query = $queryBuilder
                ->innerJoin('p.category', 'f')
                ->setMaxResults(self::NUM_ITEMS)
                ->getQuery()
                ->useQueryCache(true)
                ->useResultCache(true);

        return \AppBundle\Utils\Sorter::createPaginator($query, $page, self::NUM_ITEMS);
    }
}
