<?php

namespace AppBundle\Repository;

/**
 * serviceOptionValueDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceOptionValueDescriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
