<?php

namespace AppBundle\Repository;

/**
 * serviceOptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceOptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
