<?php

namespace AppBundle\Repository;

/**
 * serviceDiscountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceDiscountsRepository extends \Doctrine\ORM\EntityRepository
{
}
