<?php

namespace AppBundle\Repository;

/**
 * serviceSpecialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceSpecialsRepository extends \Doctrine\ORM\EntityRepository
{
}
