<?php

namespace AppBundle\Repository;

/**
 * serviceDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceDescriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
