<?php

namespace AppBundle\Repository;

/**
 * serviceOptionDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceOptionDescriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
