<?php

namespace AppBundle\Repository;

/**
 * serviceFilterRangesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceFilterRangesRepository extends \Doctrine\ORM\EntityRepository
{
}
