<?php

namespace AppBundle\Repository;

/**
 * serviceOptionValuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceOptionValuesRepository extends \Doctrine\ORM\EntityRepository
{
}
