<?php

namespace AppBundle\Repository;

/**
 * serviceFilterRangesDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceFilterRangesDescriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
