<?php

namespace AppBundle\Repository;

/**
 * serviceFilterDiscriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceFilterDiscriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
