<?php

namespace AppBundle\Repository;

/**
 * servicesFiltersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class servicesFiltersRepository extends \Doctrine\ORM\EntityRepository
{
}
