<?php

namespace AppBundle\Repository;

/**
 * SpecificPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
