<?php

namespace AppBundle\Repository;

/**
 * SupplyOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplyOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
