<?php

namespace AppBundle\Repository;

/**
 * TaxClassDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxClassDescriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
