<?php

namespace AppBundle\Repository;

/**
 * TaxRatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRatesRepository extends \Doctrine\ORM\EntityRepository
{
}
