<?php

namespace AppBundle\Repository;

/**
 * TransportOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
