<?php

namespace AppBundle\Repository;

/**
 * VendorGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
