<?php

namespace AppBundle\Repository;

/**
 * VendorDescriptonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorDescriptonsRepository extends \Doctrine\ORM\EntityRepository
{
}
