<?php

namespace AppBundle\Repository;

/**
 * WebBrowserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebBrowserRepository extends \Doctrine\ORM\EntityRepository
{
}
