<?php

namespace AppBundle\Repository;

/**
 * ZoneDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneDescriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
