<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * AddressbookchangesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressbookchangesRepository extends \Doctrine\ORM\EntityRepository
{
}
