<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * AdminSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
