<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * AdministrationLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministrationLogsRepository extends \Doctrine\ORM\EntityRepository
{
}
