<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * AdminSectionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminSectionsRepository extends \Doctrine\ORM\EntityRepository
{
}
