<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * AdministrationToolsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministrationToolsRepository extends \Doctrine\ORM\EntityRepository
{
}
