<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ApplicationVariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationVariableRepository extends \Doctrine\ORM\EntityRepository
{
}
