<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ApplicationReadLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationReadLogsRepository extends \Doctrine\ORM\EntityRepository
{
}
