<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ApplicationLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationLogsRepository extends \Doctrine\ORM\EntityRepository
{
}
