<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * AuthtokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthtokenRepository extends \Doctrine\ORM\EntityRepository
{
}
