<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * BillingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingsRepository extends \Doctrine\ORM\EntityRepository
{
}
