<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * BruteforceAttemptsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BruteforceAttemptsRepository extends \Doctrine\ORM\EntityRepository
{
}
