<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * CalendarobjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarobjectsRepository extends \Doctrine\ORM\EntityRepository
{
}
