<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * CalendarobjectsPropsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarobjectsPropsRepository extends \Doctrine\ORM\EntityRepository
{
}
