<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * CalendarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarsRepository extends \Doctrine\ORM\EntityRepository
{
}
