<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * CalendarsubscriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarsubscriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
