<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * CalendarchangesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarchangesRepository extends \Doctrine\ORM\EntityRepository
{
}
