<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * CampaignAttachmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignAttachmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
