<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * CampaignsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignsRepository extends \Doctrine\ORM\EntityRepository
{
}
