<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * CardsPropertiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardsPropertiesRepository extends \Doctrine\ORM\EntityRepository
{
}
