<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * CredentialsDefaultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CredentialsDefaultRepository extends \Doctrine\ORM\EntityRepository
{
}
