<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * DatabaseActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatabaseActionRepository extends \Doctrine\ORM\EntityRepository
{
}
