<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * DavSharesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DavSharesRepository extends \Doctrine\ORM\EntityRepository
{
}
