<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * DirectoryMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectoryMetaRepository extends \Doctrine\ORM\EntityRepository
{
}
