<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * DotunRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DotunRepository extends \Doctrine\ORM\EntityRepository
{
}
