<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * EventsToMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsToMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
