<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * FailedLoginsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FailedLoginsRepository extends \Doctrine\ORM\EntityRepository
{
}
