<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * FilesTrashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesTrashRepository extends \Doctrine\ORM\EntityRepository
{
}
