<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * FileLocksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileLocksRepository extends \Doctrine\ORM\EntityRepository
{
}
