<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * FileTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
