<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * FileCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileCacheRepository extends \Doctrine\ORM\EntityRepository
{
}
