<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * KeywordcrontrackerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordcrontrackerRepository extends \Doctrine\ORM\EntityRepository
{
}
