<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * LinkedObjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkedObjectsRepository extends \Doctrine\ORM\EntityRepository
{
}
