<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ListItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
