<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ListCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListCriteriaRepository extends \Doctrine\ORM\EntityRepository
{
}
