<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * LogMaintenaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogMaintenaceRepository extends \Doctrine\ORM\EntityRepository
{
}
