<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ManufacturersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufacturersRepository extends \Doctrine\ORM\EntityRepository
{
}
