<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * MemberRestrictionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRestrictionsRepository extends \Doctrine\ORM\EntityRepository
{
}
