<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * MimeTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MimeTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
