<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * MobileLayoutsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobileLayoutsRepository extends \Doctrine\ORM\EntityRepository
{
}
