<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * MountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MountsRepository extends \Doctrine\ORM\EntityRepository
{
}
