<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * NotificationPushtokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationPushtokensRepository extends \Doctrine\ORM\EntityRepository
{
}
