<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * Oauth2AccessTokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Oauth2AccessTokensRepository extends \Doctrine\ORM\EntityRepository
{
}
