<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ObjectContactPermissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectContactPermissionsRepository extends \Doctrine\ORM\EntityRepository
{
}
