<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ObjectTypeDependeciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectTypeDependeciesRepository extends \Doctrine\ORM\EntityRepository
{
}
