<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ObjectMembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectMembersRepository extends \Doctrine\ORM\EntityRepository
{
}
