<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ObjectTpyesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectTpyesRepository extends \Doctrine\ORM\EntityRepository
{
}
