<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ObjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectsRepository extends \Doctrine\ORM\EntityRepository
{
}
