<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ObjectRemindersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectRemindersRepository extends \Doctrine\ORM\EntityRepository
{
}
