<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ObjectPropertiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectPropertiesRepository extends \Doctrine\ORM\EntityRepository
{
}
