<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ObjectSelectcorTempValuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectSelectcorTempValuesRepository extends \Doctrine\ORM\EntityRepository
{
}
