<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ObjectReminderTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectReminderTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
