<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ObjectSubscriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectSubscriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
