<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * OrderDataTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDataTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
