<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * OrderTotalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTotalsRepository extends \Doctrine\ORM\EntityRepository
{
}
