<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * OrderServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
