<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * PermissionGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
