<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * PermissionContextsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionContextsRepository extends \Doctrine\ORM\EntityRepository
{
}
