<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * PluginsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PluginsRepository extends \Doctrine\ORM\EntityRepository
{
}
