<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * PostsToCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsToCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
