<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * PrivatedataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivatedataRepository extends \Doctrine\ORM\EntityRepository
{
}
