<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ProxylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProxylistRepository extends \Doctrine\ORM\EntityRepository
{
}
