<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * RankresultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankresultsRepository extends \Doctrine\ORM\EntityRepository
{
}
