<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ReportsSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportsSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
