<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * SchedulingobjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulingobjectsRepository extends \Doctrine\ORM\EntityRepository
{
}
