<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * SearchresultdetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchresultdetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
