<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * SearchEnginesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchEnginesRepository extends \Doctrine\ORM\EntityRepository
{
}
