<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServiceFilterRangesDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceFilterRangesDescriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
