<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServiceSpecialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceSpecialsRepository extends \Doctrine\ORM\EntityRepository
{
}
