<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServiceOptionValuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceOptionValuesRepository extends \Doctrine\ORM\EntityRepository
{
}
