<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServiceDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceDescriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
