<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServiceDiscriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceDiscriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
