<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServiceOptionValueDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceOptionValueDescriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
