<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServiceDiscountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceDiscountsRepository extends \Doctrine\ORM\EntityRepository
{
}
