<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServiceOptionDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceOptionDescriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
