<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServiceFilterRangesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceFilterRangesRepository extends \Doctrine\ORM\EntityRepository
{
}
