<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServiceTagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceTagsRepository extends \Doctrine\ORM\EntityRepository
{
}
