<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServiceOptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceOptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
