<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServicesFiltersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesFiltersRepository extends \Doctrine\ORM\EntityRepository
{
}
