<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ServicesFeaturedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesFeaturedRepository extends \Doctrine\ORM\EntityRepository
{
}
