<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ShareExternalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareExternalRepository extends \Doctrine\ORM\EntityRepository
{
}
