<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareRepository extends \Doctrine\ORM\EntityRepository
{
}
