<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * SkipdirectoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkipdirectoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
