<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * StoragesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoragesRepository extends \Doctrine\ORM\EntityRepository
{
}
