<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * SystemtagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemtagRepository extends \Doctrine\ORM\EntityRepository
{
}
