<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * TagsToPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsToPostRepository extends \Doctrine\ORM\EntityRepository
{
}
