<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * TaxClassesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxClassesRepository extends \Doctrine\ORM\EntityRepository
{
}
