<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * TaxRateDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRateDescriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
