<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * TestpluginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestpluginRepository extends \Doctrine\ORM\EntityRepository
{
}
