<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * TextsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextsRepository extends \Doctrine\ORM\EntityRepository
{
}
