<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * TopicRepliesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepliesRepository extends \Doctrine\ORM\EntityRepository
{
}
