<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * TrackersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackersRepository extends \Doctrine\ORM\EntityRepository
{
}
