<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * TranslatorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslatorsRepository extends \Doctrine\ORM\EntityRepository
{
}
