<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * TrustedServersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrustedServersRepository extends \Doctrine\ORM\EntityRepository
{
}
