<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * tWestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tWestRepository extends \Doctrine\ORM\EntityRepository
{
}
