<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * TwofactorAuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwofactorAuthRepository extends \Doctrine\ORM\EntityRepository
{
}
