<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * TwofactorBackupcodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwofactorBackupcodesRepository extends \Doctrine\ORM\EntityRepository
{
}
