<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * UrlAliasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlAliasesRepository extends \Doctrine\ORM\EntityRepository
{
}
