<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * UserNotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotificationsRepository extends \Doctrine\ORM\EntityRepository
{
}
