<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * UserSpecsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSpecsRepository extends \Doctrine\ORM\EntityRepository
{
}
