<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * UsertypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsertypesRepository extends \Doctrine\ORM\EntityRepository
{
}
