<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * VendorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorsRepository extends \Doctrine\ORM\EntityRepository
{
}
