<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ViewLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewLogRepository extends \Doctrine\ORM\EntityRepository
{
}
