<?php

namespace PartyCravings\ClientAreaBundle\Repository;

/**
 * ZonesToLocationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZonesToLocationsRepository extends \Doctrine\ORM\EntityRepository
{
}
