imports:
    - { resource: config.yml }

twig:
    globals:
        storage_link: '%gcp_bucket_url%'

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

framework:
    assets:
        base_urls:
            - https://assets.partycravings.com

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911

knp_gaufrette:
    adapters:
        gallery:
            google_cloud_storage:
                service_id: Google_Service_Storage
                bucket_name: '%gcp_bucket%'
                options:
                    acl: public
                    directory: default
    filesystems:
        gallery:
            adapter: gallery