#FOSUserBundle Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    options:
        utf8: true

#My Default Routes
google_login:
    path: /login/check-google
    options:
        i18n: false

app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    host: "{_country}.%hostname%|{_hostname}"
    defaults:
        _country: "!null"
    options:
        utf8: true

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login
    options:
        utf8: true

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login
    options:
        utf8: true

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login
    options:
        utf8: true

#FOSOAuth Server Bundle Routes
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    options:
        utf8: true

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    options:
        utf8: true
#OneUp Uploader Bundle Routes
oneup_uploader:
    resource: .
    type: uploader

#rsGaufretteBrowserBundle Routes
rs_gaufrette_browser:
    resource: "@rsGaufretteBrowserBundle/Resources/config/routing.xml"
    prefix:   /gaufrette/browser