<?php declare(strict_types = 1);

namespace App\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180714151015 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE accounts');
        $this->addSql('DROP TABLE comments');
        $this->addSql('DROP TABLE films');
        $this->addSql('DROP TABLE genre');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE currency ADD CONSTRAINT FK_6956883FB03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE currency ADD CONSTRAINT FK_6956883F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F81F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F8164D218E FOREIGN KEY (location_id) REFERENCES location (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_data ADD CONSTRAINT FK_E002C974D7707B45 FOREIGN KEY (order_status_id) REFERENCES order_statuses (id)');
        $this->addSql('ALTER TABLE order_data ADD CONSTRAINT FK_E002C9748D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE order_data ADD CONSTRAINT FK_E002C974ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE country ADD default_currency_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', ADD address_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', ADD created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', ADD updated_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', ADD hostname VARCHAR(255) DEFAULT NULL, ADD subdomain VARCHAR(255) DEFAULT NULL, ADD default_locale VARCHAR(255) NOT NULL, ADD default_language VARCHAR(255) NOT NULL, ADD info_mail VARCHAR(255) DEFAULT NULL, ADD phone VARCHAR(20) DEFAULT NULL, ADD timezone VARCHAR(255) NOT NULL, ADD is_enabled TINYINT(1) NOT NULL, ADD created DATETIME NOT NULL, ADD updated DATETIME NOT NULL, ADD tax_rate DOUBLE PRECISION NOT NULL, ADD deleted_at DATETIME DEFAULT NULL, CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\'');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966ECD792C0 FOREIGN KEY (default_currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id)');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966B03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5373C9665E237E06 ON country (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5373C966E551C011 ON country (hostname)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5373C966C1D5962E ON country (subdomain)');
        $this->addSql('CREATE INDEX IDX_5373C966ECD792C0 ON country (default_currency_id)');
        $this->addSql('CREATE INDEX IDX_5373C966F5B7AF75 ON country (address_id)');
        $this->addSql('CREATE INDEX IDX_5373C966B03A8386 ON country (created_by_id)');
        $this->addSql('CREATE INDEX IDX_5373C966896DBBDE ON country (updated_by_id)');
        $this->addSql('ALTER TABLE country_currency ADD CONSTRAINT FK_5A9CD982F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_currency ADD CONSTRAINT FK_5A9CD98238248176 FOREIGN KEY (currency_id) REFERENCES currency (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_account ADD CONSTRAINT FK_B47A0EC9F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_account ADD CONSTRAINT FK_B47A0EC99B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_pages ADD CONSTRAINT FK_8794F09FF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_pages ADD CONSTRAINT FK_8794F09F401ADD27 FOREIGN KEY (pages_id) REFERENCES pages (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_social_link ADD CONSTRAINT FK_6C2A605EF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_social_link ADD CONSTRAINT FK_6C2A605E22DFD7EC FOREIGN KEY (social_link_id) REFERENCES social_link (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party ADD CONSTRAINT FK_89954EE012469DE2 FOREIGN KEY (category_id) REFERENCES party_category (id)');
        $this->addSql('ALTER TABLE party ADD CONSTRAINT FK_89954EE0F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id)');
        $this->addSql('ALTER TABLE party ADD CONSTRAINT FK_89954EE0B03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE party ADD CONSTRAINT FK_89954EE0896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE party_pre_registration ADD CONSTRAINT FK_D8EDD967213C1059 FOREIGN KEY (party_id) REFERENCES party (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_pre_registration ADD CONSTRAINT FK_D8EDD967FB6C0FEA FOREIGN KEY (pre_registration_id) REFERENCES pre_registration (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_account ADD CONSTRAINT FK_6FC7C98F213C1059 FOREIGN KEY (party_id) REFERENCES party (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_account ADD CONSTRAINT FK_6FC7C98F9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_files ADD CONSTRAINT FK_19F060F6213C1059 FOREIGN KEY (party_id) REFERENCES party (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_files ADD CONSTRAINT FK_19F060F6A3E65B2F FOREIGN KEY (files_id) REFERENCES files (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE213C1059 FOREIGN KEY (party_id) REFERENCES party (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE66C5951B FOREIGN KEY (coupon_id) REFERENCES coupon (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FB03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE campaigns ADD CONSTRAINT FK_E3737470B03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE campaigns ADD CONSTRAINT FK_E3737470896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE campaigns ADD CONSTRAINT FK_E3737470318077BE FOREIGN KEY (uploaded_files_id) REFERENCES files (id)');
        $this->addSql('ALTER TABLE bug_reports ADD CONSTRAINT FK_AB28A5F5B03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bug_reports ADD CONSTRAINT FK_AB28A5F5896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE coupon ADD CONSTRAINT FK_64BF3F02F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE party_category ADD CONSTRAINT FK_AAE2111E79066886 FOREIGN KEY (root_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE party_category ADD CONSTRAINT FK_AAE2111E727ACA70 FOREIGN KEY (parent_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_category ADD CONSTRAINT FK_AAE2111EB03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE party_category ADD CONSTRAINT FK_AAE2111E896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE vendor ADD CONSTRAINT FK_F52233F69B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE vendor ADD CONSTRAINT FK_F52233F6F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id)');
        $this->addSql('ALTER TABLE pre_registration ADD CONSTRAINT FK_A2FEF1B99B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB79066886 FOREIGN KEY (root_id) REFERENCES location (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB727ACA70 FOREIGN KEY (parent_id) REFERENCES location (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CBF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CBB03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C179066886 FOREIGN KEY (root_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1727ACA70 FOREIGN KEY (parent_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1B03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1FDD13F95 FOREIGN KEY (tax_rate_id) REFERENCES tax_rates (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1318077BE FOREIGN KEY (uploaded_files_id) REFERENCES files (id)');
        $this->addSql('ALTER TABLE advice ADD CONSTRAINT FK_64820E8DF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_category_translations ADD CONSTRAINT FK_849333A9232D562B FOREIGN KEY (object_id) REFERENCES party_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DB03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D318077BE FOREIGN KEY (uploaded_files_id) REFERENCES files (id)');
        $this->addSql('ALTER TABLE post_tag ADD CONSTRAINT FK_5ACE3AF04B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_tag ADD CONSTRAINT FK_5ACE3AF0BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subscriber ADD CONSTRAINT FK_AD005B69F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE subscriber ADD CONSTRAINT FK_AD005B699B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2F603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD21F1DEA87 FOREIGN KEY (service_descriptions_id) REFERENCES service_descriptions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD212469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_campaigns ADD CONSTRAINT FK_BBE24E3AED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_campaigns ADD CONSTRAINT FK_BBE24E3AB0EF31F7 FOREIGN KEY (campaigns_id) REFERENCES campaigns (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_feature ADD CONSTRAINT FK_D05327FAED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_feature ADD CONSTRAINT FK_D05327FA60E4B879 FOREIGN KEY (feature_id) REFERENCES feature (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_files ADD CONSTRAINT FK_AF47ADBEED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_files ADD CONSTRAINT FK_AF47ADBEA3E65B2F FOREIGN KEY (files_id) REFERENCES files (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_details_address ADD CONSTRAINT FK_B9A084A4781F586 FOREIGN KEY (account_details_id) REFERENCES account_details (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_details_address ADD CONSTRAINT FK_B9A084AF5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_details_service ADD CONSTRAINT FK_E749FD194781F586 FOREIGN KEY (account_details_id) REFERENCES account_details (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_details_service ADD CONSTRAINT FK_E749FD19ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pages ADD CONSTRAINT FK_2074E575DE12AB56 FOREIGN KEY (created_by) REFERENCES account (id)');
        $this->addSql('ALTER TABLE pages ADD CONSTRAINT FK_2074E57516FE72E1 FOREIGN KEY (updated_by) REFERENCES account (id)');
        $this->addSql('ALTER TABLE page_translations ADD CONSTRAINT FK_78AB76C9232D562B FOREIGN KEY (object_id) REFERENCES pages (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE accounts (id INT AUTO_INCREMENT NOT NULL, firstname VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, lastname VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, plain_password VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, password VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, roles LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json_array)\', salt VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comments (id INT AUTO_INCREMENT NOT NULL, film_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, comment VARCHAR(500) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_5F9E962A567F5183 (film_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE films (id INT AUTO_INCREMENT NOT NULL, country INT DEFAULT NULL, genre INT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, updated_at DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, slug VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, description MEDIUMTEXT NOT NULL COLLATE utf8_unicode_ci, release_date DATE NOT NULL, rating INT NOT NULL, ticket_price NUMERIC(10, 2) NOT NULL, INDEX IDX_CEECCA515373C966 (country), INDEX IDX_CEECCA51835033F8 (genre), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE genre (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE films ADD CONSTRAINT FK_CEECCA515373C966 FOREIGN KEY (country) REFERENCES country (id)');
        $this->addSql('ALTER TABLE account_details_address DROP FOREIGN KEY FK_B9A084A4781F586');
        $this->addSql('ALTER TABLE account_details_address DROP FOREIGN KEY FK_B9A084AF5B7AF75');
        $this->addSql('ALTER TABLE account_details_service DROP FOREIGN KEY FK_E749FD194781F586');
        $this->addSql('ALTER TABLE account_details_service DROP FOREIGN KEY FK_E749FD19ED5CA9E6');
        $this->addSql('ALTER TABLE address DROP FOREIGN KEY FK_D4E6F81F92F3E70');
        $this->addSql('ALTER TABLE address DROP FOREIGN KEY FK_D4E6F8164D218E');
        $this->addSql('ALTER TABLE advice DROP FOREIGN KEY FK_64820E8DF92F3E70');
        $this->addSql('ALTER TABLE bug_reports DROP FOREIGN KEY FK_AB28A5F5B03A8386');
        $this->addSql('ALTER TABLE bug_reports DROP FOREIGN KEY FK_AB28A5F5896DBBDE');
        $this->addSql('ALTER TABLE campaigns DROP FOREIGN KEY FK_E3737470B03A8386');
        $this->addSql('ALTER TABLE campaigns DROP FOREIGN KEY FK_E3737470896DBBDE');
        $this->addSql('ALTER TABLE campaigns DROP FOREIGN KEY FK_E3737470318077BE');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C179066886');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1727ACA70');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1B03A8386');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1896DBBDE');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1F92F3E70');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1FDD13F95');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1318077BE');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C966ECD792C0');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C966F5B7AF75');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C966B03A8386');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C966896DBBDE');
        $this->addSql('DROP INDEX UNIQ_5373C9665E237E06 ON country');
        $this->addSql('DROP INDEX UNIQ_5373C966E551C011 ON country');
        $this->addSql('DROP INDEX UNIQ_5373C966C1D5962E ON country');
        $this->addSql('DROP INDEX IDX_5373C966ECD792C0 ON country');
        $this->addSql('DROP INDEX IDX_5373C966F5B7AF75 ON country');
        $this->addSql('DROP INDEX IDX_5373C966B03A8386 ON country');
        $this->addSql('DROP INDEX IDX_5373C966896DBBDE ON country');
        $this->addSql('ALTER TABLE country DROP default_currency_id, DROP address_id, DROP created_by_id, DROP updated_by_id, DROP hostname, DROP subdomain, DROP default_locale, DROP default_language, DROP info_mail, DROP phone, DROP timezone, DROP is_enabled, DROP created, DROP updated, DROP tax_rate, DROP deleted_at, CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE country_account DROP FOREIGN KEY FK_B47A0EC9F92F3E70');
        $this->addSql('ALTER TABLE country_account DROP FOREIGN KEY FK_B47A0EC99B6B5FBA');
        $this->addSql('ALTER TABLE country_currency DROP FOREIGN KEY FK_5A9CD982F92F3E70');
        $this->addSql('ALTER TABLE country_currency DROP FOREIGN KEY FK_5A9CD98238248176');
        $this->addSql('ALTER TABLE country_pages DROP FOREIGN KEY FK_8794F09FF92F3E70');
        $this->addSql('ALTER TABLE country_pages DROP FOREIGN KEY FK_8794F09F401ADD27');
        $this->addSql('ALTER TABLE country_social_link DROP FOREIGN KEY FK_6C2A605EF92F3E70');
        $this->addSql('ALTER TABLE country_social_link DROP FOREIGN KEY FK_6C2A605E22DFD7EC');
        $this->addSql('ALTER TABLE coupon DROP FOREIGN KEY FK_64BF3F02F92F3E70');
        $this->addSql('ALTER TABLE currency DROP FOREIGN KEY FK_6956883FB03A8386');
        $this->addSql('ALTER TABLE currency DROP FOREIGN KEY FK_6956883F896DBBDE');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CB79066886');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CB727ACA70');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CBF92F3E70');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CBB03A8386');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CB896DBBDE');
        $this->addSql('ALTER TABLE notifications DROP FOREIGN KEY FK_6000B0D3F92F3E70');
        $this->addSql('ALTER TABLE order_data DROP FOREIGN KEY FK_E002C974D7707B45');
        $this->addSql('ALTER TABLE order_data DROP FOREIGN KEY FK_E002C9748D9F6D38');
        $this->addSql('ALTER TABLE order_data DROP FOREIGN KEY FK_E002C974ED5CA9E6');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE9B6B5FBA');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE213C1059');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE66C5951B');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE896DBBDE');
        $this->addSql('ALTER TABLE page_translations DROP FOREIGN KEY FK_78AB76C9232D562B');
        $this->addSql('ALTER TABLE pages DROP FOREIGN KEY FK_2074E575DE12AB56');
        $this->addSql('ALTER TABLE pages DROP FOREIGN KEY FK_2074E57516FE72E1');
        $this->addSql('ALTER TABLE party DROP FOREIGN KEY FK_89954EE012469DE2');
        $this->addSql('ALTER TABLE party DROP FOREIGN KEY FK_89954EE0F5B7AF75');
        $this->addSql('ALTER TABLE party DROP FOREIGN KEY FK_89954EE0B03A8386');
        $this->addSql('ALTER TABLE party DROP FOREIGN KEY FK_89954EE0896DBBDE');
        $this->addSql('ALTER TABLE party_account DROP FOREIGN KEY FK_6FC7C98F213C1059');
        $this->addSql('ALTER TABLE party_account DROP FOREIGN KEY FK_6FC7C98F9B6B5FBA');
        $this->addSql('ALTER TABLE party_category DROP FOREIGN KEY FK_AAE2111E79066886');
        $this->addSql('ALTER TABLE party_category DROP FOREIGN KEY FK_AAE2111E727ACA70');
        $this->addSql('ALTER TABLE party_category DROP FOREIGN KEY FK_AAE2111EB03A8386');
        $this->addSql('ALTER TABLE party_category DROP FOREIGN KEY FK_AAE2111E896DBBDE');
        $this->addSql('ALTER TABLE party_category_translations DROP FOREIGN KEY FK_849333A9232D562B');
        $this->addSql('ALTER TABLE party_files DROP FOREIGN KEY FK_19F060F6213C1059');
        $this->addSql('ALTER TABLE party_files DROP FOREIGN KEY FK_19F060F6A3E65B2F');
        $this->addSql('ALTER TABLE party_pre_registration DROP FOREIGN KEY FK_D8EDD967213C1059');
        $this->addSql('ALTER TABLE party_pre_registration DROP FOREIGN KEY FK_D8EDD967FB6C0FEA');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DB03A8386');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8D318077BE');
        $this->addSql('ALTER TABLE post_tag DROP FOREIGN KEY FK_5ACE3AF04B89032C');
        $this->addSql('ALTER TABLE post_tag DROP FOREIGN KEY FK_5ACE3AF0BAD26311');
        $this->addSql('ALTER TABLE pre_registration DROP FOREIGN KEY FK_A2FEF1B99B6B5FBA');
        $this->addSql('ALTER TABLE reviews DROP FOREIGN KEY FK_6970EB0FB03A8386');
        $this->addSql('ALTER TABLE reviews DROP FOREIGN KEY FK_6970EB0FED5CA9E6');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD2F603EE73');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD21F1DEA87');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD212469DE2');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD2F5B7AF75');
        $this->addSql('ALTER TABLE service_campaigns DROP FOREIGN KEY FK_BBE24E3AED5CA9E6');
        $this->addSql('ALTER TABLE service_campaigns DROP FOREIGN KEY FK_BBE24E3AB0EF31F7');
        $this->addSql('ALTER TABLE service_feature DROP FOREIGN KEY FK_D05327FAED5CA9E6');
        $this->addSql('ALTER TABLE service_feature DROP FOREIGN KEY FK_D05327FA60E4B879');
        $this->addSql('ALTER TABLE service_files DROP FOREIGN KEY FK_AF47ADBEED5CA9E6');
        $this->addSql('ALTER TABLE service_files DROP FOREIGN KEY FK_AF47ADBEA3E65B2F');
        $this->addSql('ALTER TABLE subscriber DROP FOREIGN KEY FK_AD005B69F92F3E70');
        $this->addSql('ALTER TABLE subscriber DROP FOREIGN KEY FK_AD005B699B6B5FBA');
        $this->addSql('ALTER TABLE vendor DROP FOREIGN KEY FK_F52233F69B6B5FBA');
        $this->addSql('ALTER TABLE vendor DROP FOREIGN KEY FK_F52233F6F5B7AF75');
    }
}
