<?php declare(strict_types = 1);

namespace App\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180714144849 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962A567F5183');
        $this->addSql('ALTER TABLE films DROP FOREIGN KEY FK_CEECCA51835033F8');
        $this->addSql('CREATE TABLE ext_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', username VARCHAR(255) DEFAULT NULL, INDEX log_class_lookup_idx (object_class), INDEX log_date_lookup_idx (logged_at), INDEX log_user_lookup_idx (username), INDEX log_version_lookup_idx (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE account (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', account_details_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', facebook_id VARCHAR(255) DEFAULT NULL, facebook_access_token VARCHAR(255) DEFAULT NULL, google_id VARCHAR(255) DEFAULT NULL, google_access_token VARCHAR(255) DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_7D3656A492FC23A8 (username_canonical), UNIQUE INDEX UNIQ_7D3656A4A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_7D3656A4C05FB297 (confirmation_token), UNIQUE INDEX UNIQ_7D3656A44781F586 (account_details_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tax_rates (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rate DOUBLE PRECISION NOT NULL, rate_prefix VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notifications (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', country_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', t_stamp DATETIME NOT NULL, subject VARCHAR(255) NOT NULL, link VARCHAR(255) DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, INDEX IDX_6000B0D3F92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tag (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_389B7835E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE currency (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, iso_code VARCHAR(255) NOT NULL, symbol VARCHAR(255) NOT NULL, rate DOUBLE PRECISION NOT NULL, is_enabled TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_6956883FB03A8386 (created_by_id), INDEX IDX_6956883F896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE address (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', country_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', location_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', address VARCHAR(255) NOT NULL, postcode VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, vat_number VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_D4E6F81F92F3E70 (country_id), INDEX IDX_D4E6F8164D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_statuses (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_data (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', order_status_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', order_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', service_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', start_date DATETIME NOT NULL, end_date DATETIME NOT NULL, INDEX IDX_E002C974D7707B45 (order_status_id), INDEX IDX_E002C9748D9F6D38 (order_id), INDEX IDX_E002C974ED5CA9E6 (service_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE country_currency (country_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', currency_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_5A9CD982F92F3E70 (country_id), INDEX IDX_5A9CD98238248176 (currency_id), PRIMARY KEY(country_id, currency_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE country_account (country_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', account_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_B47A0EC9F92F3E70 (country_id), INDEX IDX_B47A0EC99B6B5FBA (account_id), PRIMARY KEY(country_id, account_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE country_pages (country_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', pages_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_8794F09FF92F3E70 (country_id), INDEX IDX_8794F09F401ADD27 (pages_id), PRIMARY KEY(country_id, pages_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE country_social_link (country_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', social_link_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_6C2A605EF92F3E70 (country_id), INDEX IDX_6C2A605E22DFD7EC (social_link_id), PRIMARY KEY(country_id, social_link_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE party (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', category_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', address_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, is_preregistered TINYINT(1) NOT NULL, description LONGTEXT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, is_enabled TINYINT(1) NOT NULL, date DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_89954EE0989D9B62 (slug), INDEX IDX_89954EE012469DE2 (category_id), INDEX IDX_89954EE0F5B7AF75 (address_id), INDEX IDX_89954EE0B03A8386 (created_by_id), INDEX IDX_89954EE0896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE party_pre_registration (party_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', pre_registration_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_D8EDD967213C1059 (party_id), INDEX IDX_D8EDD967FB6C0FEA (pre_registration_id), PRIMARY KEY(party_id, pre_registration_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE party_account (party_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', account_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_6FC7C98F213C1059 (party_id), INDEX IDX_6FC7C98F9B6B5FBA (account_id), PRIMARY KEY(party_id, account_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE party_files (party_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', files_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_19F060F6213C1059 (party_id), INDEX IDX_19F060F6A3E65B2F (files_id), PRIMARY KEY(party_id, files_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_descriptions (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', description LONGTEXT NOT NULL, daily_price DOUBLE PRECISION NOT NULL, daily_discount DOUBLE PRECISION DEFAULT NULL, updated DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orders (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', account_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', party_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', coupon_id INT DEFAULT NULL, updated_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', payment_method VARCHAR(255) DEFAULT NULL, payment_method_data VARCHAR(255) DEFAULT NULL, payment_method_key VARCHAR(255) DEFAULT NULL, total_discounts DOUBLE PRECISION DEFAULT NULL, total_discounts_tax_incl DOUBLE PRECISION DEFAULT NULL, total_discounts_tax_excl DOUBLE PRECISION DEFAULT NULL, total_paid DOUBLE PRECISION DEFAULT NULL, total_paid_tax_incl DOUBLE PRECISION DEFAULT NULL, total_paid_tax_excl DOUBLE PRECISION DEFAULT NULL, total_paid_real DOUBLE PRECISION DEFAULT NULL, total_cost DOUBLE PRECISION DEFAULT NULL, invoice_id VARCHAR(255) DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, created_from_ip VARCHAR(45) DEFAULT NULL, updated_from_ip VARCHAR(45) DEFAULT NULL, INDEX IDX_E52FFDEE9B6B5FBA (account_id), INDEX IDX_E52FFDEE213C1059 (party_id), INDEX IDX_E52FFDEE66C5951B (coupon_id), INDEX IDX_E52FFDEE896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE files (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', updated DATETIME DEFAULT NULL, silhouette LONGTEXT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, original_name VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(255) DEFAULT NULL, size INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reviews (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', service_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', content LONGTEXT NOT NULL, rating INT NOT NULL, created DATETIME NOT NULL, INDEX IDX_6970EB0FB03A8386 (created_by_id), INDEX IDX_6970EB0FED5CA9E6 (service_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE campaigns (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', uploaded_files_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, end_date DATETIME NOT NULL, start_date DATETIME NOT NULL, is_enabled TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_E3737470B03A8386 (created_by_id), INDEX IDX_E3737470896DBBDE (updated_by_id), INDEX IDX_E3737470318077BE (uploaded_files_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bug_reports (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', error_code INT NOT NULL, type VARCHAR(255) DEFAULT NULL, subject VARCHAR(255) DEFAULT NULL, duplicate TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_AB28A5F5B03A8386 (created_by_id), INDEX IDX_AB28A5F5896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE coupon (id INT AUTO_INCREMENT NOT NULL, country_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, amount DOUBLE PRECISION DEFAULT NULL, discount DOUBLE PRECISION DEFAULT NULL, INDEX IDX_64BF3F02F92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE party_category (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', root_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', parent_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, lft INT DEFAULT NULL, lvl INT DEFAULT NULL, rgt INT DEFAULT NULL, is_enabled TINYINT(1) NOT NULL, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_AAE2111E79066886 (root_id), INDEX IDX_AAE2111E727ACA70 (parent_id), INDEX IDX_AAE2111EB03A8386 (created_by_id), INDEX IDX_AAE2111E896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vendor (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', account_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', address_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, note LONGTEXT DEFAULT NULL, description LONGTEXT NOT NULL, is_enabled TINYINT(1) NOT NULL, created DATETIME NOT NULL, UNIQUE INDEX UNIQ_F52233F69B6B5FBA (account_id), INDEX IDX_F52233F6F5B7AF75 (address_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pre_registration (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', account_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created DATETIME NOT NULL, is_approved TINYINT(1) NOT NULL, INDEX IDX_A2FEF1B99B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE location (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', root_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', parent_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', country_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, lft INT NOT NULL, lvl INT NOT NULL, rgt INT NOT NULL, is_enabled TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UNIQ_5E9E89CB989D9B62 (slug), INDEX IDX_5E9E89CB79066886 (root_id), INDEX IDX_5E9E89CB727ACA70 (parent_id), INDEX IDX_5E9E89CBF92F3E70 (country_id), INDEX IDX_5E9E89CBB03A8386 (created_by_id), INDEX IDX_5E9E89CB896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', root_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', parent_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', country_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', tax_rate_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', uploaded_files_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', is_visible_on_home TINYINT(1) NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, slug VARCHAR(255) NOT NULL, lft INT NOT NULL, lvl INT NOT NULL, rgt INT NOT NULL, is_enabled TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_64C19C1989D9B62 (slug), INDEX IDX_64C19C179066886 (root_id), INDEX IDX_64C19C1727ACA70 (parent_id), INDEX IDX_64C19C1B03A8386 (created_by_id), INDEX IDX_64C19C1896DBBDE (updated_by_id), INDEX IDX_64C19C1F92F3E70 (country_id), INDEX IDX_64C19C1FDD13F95 (tax_rate_id), INDEX IDX_64C19C1318077BE (uploaded_files_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE advice (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', country_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', content LONGTEXT NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME NOT NULL, INDEX IDX_64820E8DF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE party_category_translations (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', object_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', locale VARCHAR(8) NOT NULL, field VARCHAR(32) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX IDX_849333A9232D562B (object_id), UNIQUE INDEX party_category_translation_idx (locale, object_id, field), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', uploaded_files_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, summary VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, created DATETIME NOT NULL, UNIQUE INDEX UNIQ_5A8A6C8D989D9B62 (slug), INDEX IDX_5A8A6C8DB03A8386 (created_by_id), INDEX IDX_5A8A6C8D318077BE (uploaded_files_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_tag (post_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', tag_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_5ACE3AF04B89032C (post_id), INDEX IDX_5ACE3AF0BAD26311 (tag_id), PRIMARY KEY(post_id, tag_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subscriber (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', country_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', account_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', endpoint LONGTEXT NOT NULL, browserKey VARCHAR(255) NOT NULL, authSecret VARCHAR(255) NOT NULL, created DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, enabled TINYINT(1) NOT NULL, INDEX IDX_AD005B69F92F3E70 (country_id), INDEX IDX_AD005B699B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', vendor_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', service_descriptions_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', category_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', address_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, is_enabled TINYINT(1) NOT NULL, created DATETIME NOT NULL, UNIQUE INDEX UNIQ_E19D9AD2989D9B62 (slug), INDEX IDX_E19D9AD2F603EE73 (vendor_id), UNIQUE INDEX UNIQ_E19D9AD21F1DEA87 (service_descriptions_id), INDEX IDX_E19D9AD212469DE2 (category_id), INDEX IDX_E19D9AD2F5B7AF75 (address_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_campaigns (service_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', campaigns_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_BBE24E3AED5CA9E6 (service_id), INDEX IDX_BBE24E3AB0EF31F7 (campaigns_id), PRIMARY KEY(service_id, campaigns_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_feature (service_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', feature_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_D05327FAED5CA9E6 (service_id), INDEX IDX_D05327FA60E4B879 (feature_id), PRIMARY KEY(service_id, feature_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_files (service_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', files_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_AF47ADBEED5CA9E6 (service_id), INDEX IDX_AF47ADBEA3E65B2F (files_id), PRIMARY KEY(service_id, files_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE account_details (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', birthday DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', firstname VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) DEFAULT NULL, newsletter_signed TINYINT(1) NOT NULL, created_from_ip VARCHAR(45) DEFAULT NULL, updated_from_ip VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE account_details_address (account_details_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', address_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_B9A084A4781F586 (account_details_id), INDEX IDX_B9A084AF5B7AF75 (address_id), PRIMARY KEY(account_details_id, address_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE account_details_service (account_details_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', service_id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', INDEX IDX_E749FD194781F586 (account_details_id), INDEX IDX_E749FD19ED5CA9E6 (service_id), PRIMARY KEY(account_details_id, service_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pages (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', created_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', updated_by CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, slug VARCHAR(255) NOT NULL, is_enabled TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_2074E575989D9B62 (slug), INDEX IDX_2074E575DE12AB56 (created_by), INDEX IDX_2074E57516FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE social_link (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, link VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page_translations (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', object_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', locale VARCHAR(8) NOT NULL, field VARCHAR(32) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX IDX_78AB76C9232D562B (object_id), UNIQUE INDEX page_translation_idx (locale, object_id, field), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE feature (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_1FD775665E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE imports (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', model_id INT DEFAULT NULL, model_type VARCHAR(255) DEFAULT NULL, t_stamp DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A44781F586 FOREIGN KEY (account_details_id) REFERENCES account_details (id)');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE currency ADD CONSTRAINT FK_6956883FB03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE currency ADD CONSTRAINT FK_6956883F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F81F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F8164D218E FOREIGN KEY (location_id) REFERENCES location (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_data ADD CONSTRAINT FK_E002C974D7707B45 FOREIGN KEY (order_status_id) REFERENCES order_statuses (id)');
        $this->addSql('ALTER TABLE order_data ADD CONSTRAINT FK_E002C9748D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE order_data ADD CONSTRAINT FK_E002C974ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE country_currency ADD CONSTRAINT FK_5A9CD982F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_currency ADD CONSTRAINT FK_5A9CD98238248176 FOREIGN KEY (currency_id) REFERENCES currency (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_account ADD CONSTRAINT FK_B47A0EC9F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_account ADD CONSTRAINT FK_B47A0EC99B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_pages ADD CONSTRAINT FK_8794F09FF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_pages ADD CONSTRAINT FK_8794F09F401ADD27 FOREIGN KEY (pages_id) REFERENCES pages (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_social_link ADD CONSTRAINT FK_6C2A605EF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country_social_link ADD CONSTRAINT FK_6C2A605E22DFD7EC FOREIGN KEY (social_link_id) REFERENCES social_link (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party ADD CONSTRAINT FK_89954EE012469DE2 FOREIGN KEY (category_id) REFERENCES party_category (id)');
        $this->addSql('ALTER TABLE party ADD CONSTRAINT FK_89954EE0F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id)');
        $this->addSql('ALTER TABLE party ADD CONSTRAINT FK_89954EE0B03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE party ADD CONSTRAINT FK_89954EE0896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE party_pre_registration ADD CONSTRAINT FK_D8EDD967213C1059 FOREIGN KEY (party_id) REFERENCES party (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_pre_registration ADD CONSTRAINT FK_D8EDD967FB6C0FEA FOREIGN KEY (pre_registration_id) REFERENCES pre_registration (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_account ADD CONSTRAINT FK_6FC7C98F213C1059 FOREIGN KEY (party_id) REFERENCES party (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_account ADD CONSTRAINT FK_6FC7C98F9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_files ADD CONSTRAINT FK_19F060F6213C1059 FOREIGN KEY (party_id) REFERENCES party (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_files ADD CONSTRAINT FK_19F060F6A3E65B2F FOREIGN KEY (files_id) REFERENCES files (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE213C1059 FOREIGN KEY (party_id) REFERENCES party (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE66C5951B FOREIGN KEY (coupon_id) REFERENCES coupon (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FB03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE campaigns ADD CONSTRAINT FK_E3737470B03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE campaigns ADD CONSTRAINT FK_E3737470896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE campaigns ADD CONSTRAINT FK_E3737470318077BE FOREIGN KEY (uploaded_files_id) REFERENCES files (id)');
        $this->addSql('ALTER TABLE bug_reports ADD CONSTRAINT FK_AB28A5F5B03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bug_reports ADD CONSTRAINT FK_AB28A5F5896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE coupon ADD CONSTRAINT FK_64BF3F02F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE party_category ADD CONSTRAINT FK_AAE2111E79066886 FOREIGN KEY (root_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE party_category ADD CONSTRAINT FK_AAE2111E727ACA70 FOREIGN KEY (parent_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_category ADD CONSTRAINT FK_AAE2111EB03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE party_category ADD CONSTRAINT FK_AAE2111E896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE vendor ADD CONSTRAINT FK_F52233F69B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE vendor ADD CONSTRAINT FK_F52233F6F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id)');
        $this->addSql('ALTER TABLE pre_registration ADD CONSTRAINT FK_A2FEF1B99B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB79066886 FOREIGN KEY (root_id) REFERENCES location (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB727ACA70 FOREIGN KEY (parent_id) REFERENCES location (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CBF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CBB03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C179066886 FOREIGN KEY (root_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1727ACA70 FOREIGN KEY (parent_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1B03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1FDD13F95 FOREIGN KEY (tax_rate_id) REFERENCES tax_rates (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1318077BE FOREIGN KEY (uploaded_files_id) REFERENCES files (id)');
        $this->addSql('ALTER TABLE advice ADD CONSTRAINT FK_64820E8DF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE party_category_translations ADD CONSTRAINT FK_849333A9232D562B FOREIGN KEY (object_id) REFERENCES party_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DB03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D318077BE FOREIGN KEY (uploaded_files_id) REFERENCES files (id)');
        $this->addSql('ALTER TABLE post_tag ADD CONSTRAINT FK_5ACE3AF04B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_tag ADD CONSTRAINT FK_5ACE3AF0BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subscriber ADD CONSTRAINT FK_AD005B69F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE subscriber ADD CONSTRAINT FK_AD005B699B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2F603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD21F1DEA87 FOREIGN KEY (service_descriptions_id) REFERENCES service_descriptions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD212469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_campaigns ADD CONSTRAINT FK_BBE24E3AED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_campaigns ADD CONSTRAINT FK_BBE24E3AB0EF31F7 FOREIGN KEY (campaigns_id) REFERENCES campaigns (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_feature ADD CONSTRAINT FK_D05327FAED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_feature ADD CONSTRAINT FK_D05327FA60E4B879 FOREIGN KEY (feature_id) REFERENCES feature (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_files ADD CONSTRAINT FK_AF47ADBEED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_files ADD CONSTRAINT FK_AF47ADBEA3E65B2F FOREIGN KEY (files_id) REFERENCES files (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_details_address ADD CONSTRAINT FK_B9A084A4781F586 FOREIGN KEY (account_details_id) REFERENCES account_details (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_details_address ADD CONSTRAINT FK_B9A084AF5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_details_service ADD CONSTRAINT FK_E749FD194781F586 FOREIGN KEY (account_details_id) REFERENCES account_details (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_details_service ADD CONSTRAINT FK_E749FD19ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pages ADD CONSTRAINT FK_2074E575DE12AB56 FOREIGN KEY (created_by) REFERENCES account (id)');
        $this->addSql('ALTER TABLE pages ADD CONSTRAINT FK_2074E57516FE72E1 FOREIGN KEY (updated_by) REFERENCES account (id)');
        $this->addSql('ALTER TABLE page_translations ADD CONSTRAINT FK_78AB76C9232D562B FOREIGN KEY (object_id) REFERENCES pages (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE accounts');
        $this->addSql('DROP TABLE comments');
        $this->addSql('DROP TABLE films');
        $this->addSql('DROP TABLE genre');
        $this->addSql('ALTER TABLE country ADD default_currency_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', ADD address_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', ADD created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', ADD updated_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', ADD hostname VARCHAR(255) DEFAULT NULL, ADD subdomain VARCHAR(255) DEFAULT NULL, ADD default_locale VARCHAR(255) NOT NULL, ADD default_language VARCHAR(255) NOT NULL, ADD info_mail VARCHAR(255) DEFAULT NULL, ADD phone VARCHAR(20) DEFAULT NULL, ADD timezone VARCHAR(255) NOT NULL, ADD is_enabled TINYINT(1) NOT NULL, ADD created DATETIME NOT NULL, ADD updated DATETIME NOT NULL, ADD tax_rate DOUBLE PRECISION NOT NULL, ADD deleted_at DATETIME DEFAULT NULL, CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\'');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966ECD792C0 FOREIGN KEY (default_currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id)');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966B03A8386 FOREIGN KEY (created_by_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966896DBBDE FOREIGN KEY (updated_by_id) REFERENCES account (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5373C9665E237E06 ON country (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5373C966E551C011 ON country (hostname)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5373C966C1D5962E ON country (subdomain)');
        $this->addSql('CREATE INDEX IDX_5373C966ECD792C0 ON country (default_currency_id)');
        $this->addSql('CREATE INDEX IDX_5373C966F5B7AF75 ON country (address_id)');
        $this->addSql('CREATE INDEX IDX_5373C966B03A8386 ON country (created_by_id)');
        $this->addSql('CREATE INDEX IDX_5373C966896DBBDE ON country (updated_by_id)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE currency DROP FOREIGN KEY FK_6956883FB03A8386');
        $this->addSql('ALTER TABLE currency DROP FOREIGN KEY FK_6956883F896DBBDE');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C966B03A8386');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C966896DBBDE');
        $this->addSql('ALTER TABLE country_account DROP FOREIGN KEY FK_B47A0EC99B6B5FBA');
        $this->addSql('ALTER TABLE party DROP FOREIGN KEY FK_89954EE0B03A8386');
        $this->addSql('ALTER TABLE party DROP FOREIGN KEY FK_89954EE0896DBBDE');
        $this->addSql('ALTER TABLE party_account DROP FOREIGN KEY FK_6FC7C98F9B6B5FBA');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE9B6B5FBA');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE896DBBDE');
        $this->addSql('ALTER TABLE reviews DROP FOREIGN KEY FK_6970EB0FB03A8386');
        $this->addSql('ALTER TABLE campaigns DROP FOREIGN KEY FK_E3737470B03A8386');
        $this->addSql('ALTER TABLE campaigns DROP FOREIGN KEY FK_E3737470896DBBDE');
        $this->addSql('ALTER TABLE bug_reports DROP FOREIGN KEY FK_AB28A5F5B03A8386');
        $this->addSql('ALTER TABLE bug_reports DROP FOREIGN KEY FK_AB28A5F5896DBBDE');
        $this->addSql('ALTER TABLE party_category DROP FOREIGN KEY FK_AAE2111EB03A8386');
        $this->addSql('ALTER TABLE party_category DROP FOREIGN KEY FK_AAE2111E896DBBDE');
        $this->addSql('ALTER TABLE vendor DROP FOREIGN KEY FK_F52233F69B6B5FBA');
        $this->addSql('ALTER TABLE pre_registration DROP FOREIGN KEY FK_A2FEF1B99B6B5FBA');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CBB03A8386');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CB896DBBDE');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1B03A8386');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1896DBBDE');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DB03A8386');
        $this->addSql('ALTER TABLE subscriber DROP FOREIGN KEY FK_AD005B699B6B5FBA');
        $this->addSql('ALTER TABLE pages DROP FOREIGN KEY FK_2074E575DE12AB56');
        $this->addSql('ALTER TABLE pages DROP FOREIGN KEY FK_2074E57516FE72E1');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1FDD13F95');
        $this->addSql('ALTER TABLE post_tag DROP FOREIGN KEY FK_5ACE3AF0BAD26311');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C966ECD792C0');
        $this->addSql('ALTER TABLE country_currency DROP FOREIGN KEY FK_5A9CD98238248176');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C966F5B7AF75');
        $this->addSql('ALTER TABLE party DROP FOREIGN KEY FK_89954EE0F5B7AF75');
        $this->addSql('ALTER TABLE vendor DROP FOREIGN KEY FK_F52233F6F5B7AF75');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD2F5B7AF75');
        $this->addSql('ALTER TABLE account_details_address DROP FOREIGN KEY FK_B9A084AF5B7AF75');
        $this->addSql('ALTER TABLE order_data DROP FOREIGN KEY FK_E002C974D7707B45');
        $this->addSql('ALTER TABLE party_pre_registration DROP FOREIGN KEY FK_D8EDD967213C1059');
        $this->addSql('ALTER TABLE party_account DROP FOREIGN KEY FK_6FC7C98F213C1059');
        $this->addSql('ALTER TABLE party_files DROP FOREIGN KEY FK_19F060F6213C1059');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE213C1059');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD21F1DEA87');
        $this->addSql('ALTER TABLE order_data DROP FOREIGN KEY FK_E002C9748D9F6D38');
        $this->addSql('ALTER TABLE party_files DROP FOREIGN KEY FK_19F060F6A3E65B2F');
        $this->addSql('ALTER TABLE campaigns DROP FOREIGN KEY FK_E3737470318077BE');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1318077BE');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8D318077BE');
        $this->addSql('ALTER TABLE service_files DROP FOREIGN KEY FK_AF47ADBEA3E65B2F');
        $this->addSql('ALTER TABLE service_campaigns DROP FOREIGN KEY FK_BBE24E3AB0EF31F7');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE66C5951B');
        $this->addSql('ALTER TABLE party DROP FOREIGN KEY FK_89954EE012469DE2');
        $this->addSql('ALTER TABLE party_category_translations DROP FOREIGN KEY FK_849333A9232D562B');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD2F603EE73');
        $this->addSql('ALTER TABLE party_pre_registration DROP FOREIGN KEY FK_D8EDD967FB6C0FEA');
        $this->addSql('ALTER TABLE address DROP FOREIGN KEY FK_D4E6F8164D218E');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CB79066886');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CB727ACA70');
        $this->addSql('ALTER TABLE party_category DROP FOREIGN KEY FK_AAE2111E79066886');
        $this->addSql('ALTER TABLE party_category DROP FOREIGN KEY FK_AAE2111E727ACA70');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C179066886');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1727ACA70');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD212469DE2');
        $this->addSql('ALTER TABLE post_tag DROP FOREIGN KEY FK_5ACE3AF04B89032C');
        $this->addSql('ALTER TABLE order_data DROP FOREIGN KEY FK_E002C974ED5CA9E6');
        $this->addSql('ALTER TABLE reviews DROP FOREIGN KEY FK_6970EB0FED5CA9E6');
        $this->addSql('ALTER TABLE service_campaigns DROP FOREIGN KEY FK_BBE24E3AED5CA9E6');
        $this->addSql('ALTER TABLE service_feature DROP FOREIGN KEY FK_D05327FAED5CA9E6');
        $this->addSql('ALTER TABLE service_files DROP FOREIGN KEY FK_AF47ADBEED5CA9E6');
        $this->addSql('ALTER TABLE account_details_service DROP FOREIGN KEY FK_E749FD19ED5CA9E6');
        $this->addSql('ALTER TABLE account DROP FOREIGN KEY FK_7D3656A44781F586');
        $this->addSql('ALTER TABLE account_details_address DROP FOREIGN KEY FK_B9A084A4781F586');
        $this->addSql('ALTER TABLE account_details_service DROP FOREIGN KEY FK_E749FD194781F586');
        $this->addSql('ALTER TABLE country_pages DROP FOREIGN KEY FK_8794F09F401ADD27');
        $this->addSql('ALTER TABLE page_translations DROP FOREIGN KEY FK_78AB76C9232D562B');
        $this->addSql('ALTER TABLE country_social_link DROP FOREIGN KEY FK_6C2A605E22DFD7EC');
        $this->addSql('ALTER TABLE service_feature DROP FOREIGN KEY FK_D05327FA60E4B879');
        $this->addSql('CREATE TABLE accounts (id INT AUTO_INCREMENT NOT NULL, firstname VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, lastname VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, plain_password VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, password VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, roles LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json_array)\', salt VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comments (id INT AUTO_INCREMENT NOT NULL, film_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, comment VARCHAR(500) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_5F9E962A567F5183 (film_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE films (id INT AUTO_INCREMENT NOT NULL, country INT DEFAULT NULL, genre INT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, updated_at DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, slug VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, description MEDIUMTEXT NOT NULL COLLATE utf8_unicode_ci, release_date DATE NOT NULL, rating INT NOT NULL, ticket_price NUMERIC(10, 2) NOT NULL, INDEX IDX_CEECCA515373C966 (country), INDEX IDX_CEECCA51835033F8 (genre), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE genre (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A567F5183 FOREIGN KEY (film_id) REFERENCES films (id)');
        $this->addSql('ALTER TABLE films ADD CONSTRAINT FK_CEECCA515373C966 FOREIGN KEY (country) REFERENCES country (id)');
        $this->addSql('ALTER TABLE films ADD CONSTRAINT FK_CEECCA51835033F8 FOREIGN KEY (genre) REFERENCES genre (id)');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE account');
        $this->addSql('DROP TABLE tax_rates');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE currency');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE order_statuses');
        $this->addSql('DROP TABLE order_data');
        $this->addSql('DROP TABLE country_currency');
        $this->addSql('DROP TABLE country_account');
        $this->addSql('DROP TABLE country_pages');
        $this->addSql('DROP TABLE country_social_link');
        $this->addSql('DROP TABLE party');
        $this->addSql('DROP TABLE party_pre_registration');
        $this->addSql('DROP TABLE party_account');
        $this->addSql('DROP TABLE party_files');
        $this->addSql('DROP TABLE service_descriptions');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE files');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE campaigns');
        $this->addSql('DROP TABLE bug_reports');
        $this->addSql('DROP TABLE coupon');
        $this->addSql('DROP TABLE party_category');
        $this->addSql('DROP TABLE vendor');
        $this->addSql('DROP TABLE pre_registration');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE advice');
        $this->addSql('DROP TABLE party_category_translations');
        $this->addSql('DROP TABLE post');
        $this->addSql('DROP TABLE post_tag');
        $this->addSql('DROP TABLE subscriber');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE service_campaigns');
        $this->addSql('DROP TABLE service_feature');
        $this->addSql('DROP TABLE service_files');
        $this->addSql('DROP TABLE account_details');
        $this->addSql('DROP TABLE account_details_address');
        $this->addSql('DROP TABLE account_details_service');
        $this->addSql('DROP TABLE pages');
        $this->addSql('DROP TABLE social_link');
        $this->addSql('DROP TABLE page_translations');
        $this->addSql('DROP TABLE feature');
        $this->addSql('DROP TABLE imports');
        $this->addSql('DROP INDEX UNIQ_5373C9665E237E06 ON country');
        $this->addSql('DROP INDEX UNIQ_5373C966E551C011 ON country');
        $this->addSql('DROP INDEX UNIQ_5373C966C1D5962E ON country');
        $this->addSql('DROP INDEX IDX_5373C966ECD792C0 ON country');
        $this->addSql('DROP INDEX IDX_5373C966F5B7AF75 ON country');
        $this->addSql('DROP INDEX IDX_5373C966B03A8386 ON country');
        $this->addSql('DROP INDEX IDX_5373C966896DBBDE ON country');
        $this->addSql('ALTER TABLE country DROP default_currency_id, DROP address_id, DROP created_by_id, DROP updated_by_id, DROP hostname, DROP subdomain, DROP default_locale, DROP default_language, DROP info_mail, DROP phone, DROP timezone, DROP is_enabled, DROP created, DROP updated, DROP tax_rate, DROP deleted_at, CHANGE id id INT AUTO_INCREMENT NOT NULL');
    }
}
